// Oanarina Archi Tool — GPL-3.0-or-later
// IFC4 entity attribute table (ifcXML, schema validation) (generated from IfcOpenShell's schema definition, LGPL-3.0-or-later,
// (c) IfcOpenShell contributors; only names and attribute kinds are used). Line format:
// Entity|Supertype|Attribute:kind,…|derived mask of all attributes[|abstract]. Kinds:
// s string, r real, u number (integer or real), i integer, b boolean/logical, x binary, n enumeration, e entity (or select of entities), v select that
// may hold a typed value, L<k> list of simple values, M<k> list of lists, E list of entities / select values;
// a trailing ? marks an OPTIONAL attribute.
import Foundation

extension IFCSchemaTable {
    static let ifc4Table = """
IfcActionRequest|IfcControl|PredefinedType:n?,Status:s?,LongDescription:s?|000000000
IfcActor|IfcObject|TheActor:e|000000
IfcActorRole||Role:n,UserDefinedRole:s?,Description:s?|000
IfcActuator|IfcDistributionControlElement|PredefinedType:n?|000000000
IfcActuatorType|IfcDistributionControlElementType|PredefinedType:n|0000000000
IfcAddress||Purpose:n?,Description:s?,UserDefinedPurpose:s?|000|abstract
IfcAdvancedBrep|IfcManifoldSolidBrep||0
IfcAdvancedBrepWithVoids|IfcAdvancedBrep|Voids:E|00
IfcAdvancedFace|IfcFaceSurface||000
IfcAirTerminal|IfcFlowTerminal|PredefinedType:n?|000000000
IfcAirTerminalBox|IfcFlowController|PredefinedType:n?|000000000
IfcAirTerminalBoxType|IfcFlowControllerType|PredefinedType:n|0000000000
IfcAirTerminalType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcAirToAirHeatRecovery|IfcEnergyConversionDevice|PredefinedType:n?|000000000
IfcAirToAirHeatRecoveryType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcAlarm|IfcDistributionControlElement|PredefinedType:n?|000000000
IfcAlarmType|IfcDistributionControlElementType|PredefinedType:n|0000000000
IfcAnnotation|IfcProduct||0000000
IfcAnnotationFillArea|IfcGeometricRepresentationItem|OuterBoundary:e,InnerBoundaries:E?|00
IfcApplication||ApplicationDeveloper:e,Version:s,ApplicationFullName:s,ApplicationIdentifier:s|0000
IfcAppliedValue||Name:s?,Description:s?,AppliedValue:v?,UnitBasis:e?,ApplicableDate:s?,FixedUntilDate:s?,Category:s?,Condition:s?,ArithmeticOperator:n?,Components:E?|0000000000
IfcApproval||Identifier:s?,Name:s?,Description:s?,TimeOfApproval:s?,Status:s?,Level:s?,Qualifier:s?,RequestingApproval:e?,GivingApproval:e?|000000000
IfcApprovalRelationship|IfcResourceLevelRelationship|RelatingApproval:e,RelatedApprovals:E|0000
IfcArbitraryClosedProfileDef|IfcProfileDef|OuterCurve:e|000
IfcArbitraryOpenProfileDef|IfcProfileDef|Curve:e|000
IfcArbitraryProfileDefWithVoids|IfcArbitraryClosedProfileDef|InnerCurves:E|0000
IfcAsset|IfcGroup|Identification:s?,OriginalValue:e?,CurrentValue:e?,TotalReplacementCost:e?,Owner:e?,User:e?,ResponsiblePerson:e?,IncorporationDate:s?,DepreciatedValue:e?|00000000000000
IfcAsymmetricIShapeProfileDef|IfcParameterizedProfileDef|BottomFlangeWidth:r,OverallDepth:r,WebThickness:r,BottomFlangeThickness:r,BottomFlangeFilletRadius:r?,TopFlangeWidth:r,TopFlangeThickness:r?,TopFlangeFilletRadius:r?,BottomFlangeEdgeRadius:r?,BottomFlangeSlope:r?,TopFlangeEdgeRadius:r?,TopFlangeSlope:r?|000000000000000
IfcAudioVisualAppliance|IfcFlowTerminal|PredefinedType:n?|000000000
IfcAudioVisualApplianceType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcAxis1Placement|IfcPlacement|Axis:e?|00
IfcAxis2Placement2D|IfcPlacement|RefDirection:e?|00
IfcAxis2Placement3D|IfcPlacement|Axis:e?,RefDirection:e?|000
IfcBSplineCurve|IfcBoundedCurve|Degree:i,ControlPointsList:E,CurveForm:n,ClosedCurve:b,SelfIntersect:b|00000|abstract
IfcBSplineCurveWithKnots|IfcBSplineCurve|KnotMultiplicities:Li,Knots:Lr,KnotSpec:n|00000000
IfcBSplineSurface|IfcBoundedSurface|UDegree:i,VDegree:i,ControlPointsList:E,SurfaceForm:n,UClosed:b,VClosed:b,SelfIntersect:b|0000000|abstract
IfcBSplineSurfaceWithKnots|IfcBSplineSurface|UMultiplicities:Li,VMultiplicities:Li,UKnots:Lr,VKnots:Lr,KnotSpec:n|000000000000
IfcBeam|IfcBuildingElement|PredefinedType:n?|000000000
IfcBeamStandardCase|IfcBeam||000000000
IfcBeamType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcBlobTexture|IfcSurfaceTexture|RasterFormat:s,RasterCode:x|0000000
IfcBlock|IfcCsgPrimitive3D|XLength:r,YLength:r,ZLength:r|0000
IfcBoiler|IfcEnergyConversionDevice|PredefinedType:n?|000000000
IfcBoilerType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcBooleanClippingResult|IfcBooleanResult||000
IfcBooleanResult|IfcGeometricRepresentationItem|Operator:n,FirstOperand:e,SecondOperand:e|000
IfcBoundaryCondition||Name:s?|0|abstract
IfcBoundaryCurve|IfcCompositeCurveOnSurface||00
IfcBoundaryEdgeCondition|IfcBoundaryCondition|TranslationalStiffnessByLengthX:v?,TranslationalStiffnessByLengthY:v?,TranslationalStiffnessByLengthZ:v?,RotationalStiffnessByLengthX:v?,RotationalStiffnessByLengthY:v?,RotationalStiffnessByLengthZ:v?|0000000
IfcBoundaryFaceCondition|IfcBoundaryCondition|TranslationalStiffnessByAreaX:v?,TranslationalStiffnessByAreaY:v?,TranslationalStiffnessByAreaZ:v?|0000
IfcBoundaryNodeCondition|IfcBoundaryCondition|TranslationalStiffnessX:v?,TranslationalStiffnessY:v?,TranslationalStiffnessZ:v?,RotationalStiffnessX:v?,RotationalStiffnessY:v?,RotationalStiffnessZ:v?|0000000
IfcBoundaryNodeConditionWarping|IfcBoundaryNodeCondition|WarpingStiffness:v?|00000000
IfcBoundedCurve|IfcCurve|||abstract
IfcBoundedSurface|IfcSurface|||abstract
IfcBoundingBox|IfcGeometricRepresentationItem|Corner:e,XDim:r,YDim:r,ZDim:r|0000
IfcBoxedHalfSpace|IfcHalfSpaceSolid|Enclosure:e|000
IfcBuilding|IfcSpatialStructureElement|ElevationOfRefHeight:r?,ElevationOfTerrain:r?,BuildingAddress:e?|000000000000
IfcBuildingElement|IfcElement||00000000|abstract
IfcBuildingElementPart|IfcElementComponent|PredefinedType:n?|000000000
IfcBuildingElementPartType|IfcElementComponentType|PredefinedType:n|0000000000
IfcBuildingElementProxy|IfcBuildingElement|PredefinedType:n?|000000000
IfcBuildingElementProxyType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcBuildingElementType|IfcElementType||000000000|abstract
IfcBuildingStorey|IfcSpatialStructureElement|Elevation:r?|0000000000
IfcBuildingSystem|IfcSystem|PredefinedType:n?,LongName:s?|0000000
IfcBurner|IfcEnergyConversionDevice|PredefinedType:n?|000000000
IfcBurnerType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcCShapeProfileDef|IfcParameterizedProfileDef|Depth:r,Width:r,WallThickness:r,Girth:r,InternalFilletRadius:r?|00000000
IfcCableCarrierFitting|IfcFlowFitting|PredefinedType:n?|000000000
IfcCableCarrierFittingType|IfcFlowFittingType|PredefinedType:n|0000000000
IfcCableCarrierSegment|IfcFlowSegment|PredefinedType:n?|000000000
IfcCableCarrierSegmentType|IfcFlowSegmentType|PredefinedType:n|0000000000
IfcCableFitting|IfcFlowFitting|PredefinedType:n?|000000000
IfcCableFittingType|IfcFlowFittingType|PredefinedType:n|0000000000
IfcCableSegment|IfcFlowSegment|PredefinedType:n?|000000000
IfcCableSegmentType|IfcFlowSegmentType|PredefinedType:n|0000000000
IfcCartesianPoint|IfcPoint|Coordinates:Lr|0
IfcCartesianPointList|IfcGeometricRepresentationItem|||abstract
IfcCartesianPointList2D|IfcCartesianPointList|CoordList:Mr|0
IfcCartesianPointList3D|IfcCartesianPointList|CoordList:Mr|0
IfcCartesianTransformationOperator|IfcGeometricRepresentationItem|Axis1:e?,Axis2:e?,LocalOrigin:e,Scale:r?|0000|abstract
IfcCartesianTransformationOperator2D|IfcCartesianTransformationOperator||0000
IfcCartesianTransformationOperator2DnonUniform|IfcCartesianTransformationOperator2D|Scale2:r?|00000
IfcCartesianTransformationOperator3D|IfcCartesianTransformationOperator|Axis3:e?|00000
IfcCartesianTransformationOperator3DnonUniform|IfcCartesianTransformationOperator3D|Scale2:r?,Scale3:r?|0000000
IfcCenterLineProfileDef|IfcArbitraryOpenProfileDef|Thickness:r|0000
IfcChiller|IfcEnergyConversionDevice|PredefinedType:n?|000000000
IfcChillerType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcChimney|IfcBuildingElement|PredefinedType:n?|000000000
IfcChimneyType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcCircle|IfcConic|Radius:r|00
IfcCircleHollowProfileDef|IfcCircleProfileDef|WallThickness:r|00000
IfcCircleProfileDef|IfcParameterizedProfileDef|Radius:r|0000
IfcCivilElement|IfcElement||00000000
IfcCivilElementType|IfcElementType||000000000
IfcClassification|IfcExternalInformation|Source:s?,Edition:s?,EditionDate:s?,Name:s,Description:s?,Location:s?,ReferenceTokens:Ls?|0000000
IfcClassificationReference|IfcExternalReference|ReferencedSource:e?,Description:s?,Sort:s?|000000
IfcClosedShell|IfcConnectedFaceSet||0
IfcCoil|IfcEnergyConversionDevice|PredefinedType:n?|000000000
IfcCoilType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcColourRgb|IfcColourSpecification|Red:r,Green:r,Blue:r|0000
IfcColourRgbList|IfcPresentationItem|ColourList:Mr|0
IfcColourSpecification|IfcPresentationItem|Name:s?|0|abstract
IfcColumn|IfcBuildingElement|PredefinedType:n?|000000000
IfcColumnStandardCase|IfcColumn||000000000
IfcColumnType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcCommunicationsAppliance|IfcFlowTerminal|PredefinedType:n?|000000000
IfcCommunicationsApplianceType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcComplexProperty|IfcProperty|UsageName:s,HasProperties:E|0000
IfcComplexPropertyTemplate|IfcPropertyTemplate|UsageName:s?,TemplateType:n?,HasPropertyTemplates:E?|0000000
IfcCompositeCurve|IfcBoundedCurve|Segments:E,SelfIntersect:b|00
IfcCompositeCurveOnSurface|IfcCompositeCurve||00
IfcCompositeCurveSegment|IfcGeometricRepresentationItem|Transition:n,SameSense:b,ParentCurve:e|000
IfcCompositeProfileDef|IfcProfileDef|Profiles:E,Label:s?|0000
IfcCompressor|IfcFlowMovingDevice|PredefinedType:n?|000000000
IfcCompressorType|IfcFlowMovingDeviceType|PredefinedType:n|0000000000
IfcCondenser|IfcEnergyConversionDevice|PredefinedType:n?|000000000
IfcCondenserType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcConic|IfcCurve|Position:e|0|abstract
IfcConnectedFaceSet|IfcTopologicalRepresentationItem|CfsFaces:E|0
IfcConnectionCurveGeometry|IfcConnectionGeometry|CurveOnRelatingElement:e,CurveOnRelatedElement:e?|00
IfcConnectionGeometry||||abstract
IfcConnectionPointEccentricity|IfcConnectionPointGeometry|EccentricityInX:r?,EccentricityInY:r?,EccentricityInZ:r?|00000
IfcConnectionPointGeometry|IfcConnectionGeometry|PointOnRelatingElement:e,PointOnRelatedElement:e?|00
IfcConnectionSurfaceGeometry|IfcConnectionGeometry|SurfaceOnRelatingElement:e,SurfaceOnRelatedElement:e?|00
IfcConnectionVolumeGeometry|IfcConnectionGeometry|VolumeOnRelatingElement:e,VolumeOnRelatedElement:e?|00
IfcConstraint||Name:s,Description:s?,ConstraintGrade:n,ConstraintSource:s?,CreatingActor:e?,CreationTime:s?,UserDefinedGrade:s?|0000000|abstract
IfcConstructionEquipmentResource|IfcConstructionResource|PredefinedType:n?|00000000000
IfcConstructionEquipmentResourceType|IfcConstructionResourceType|PredefinedType:n|000000000000
IfcConstructionMaterialResource|IfcConstructionResource|PredefinedType:n?|00000000000
IfcConstructionMaterialResourceType|IfcConstructionResourceType|PredefinedType:n|000000000000
IfcConstructionProductResource|IfcConstructionResource|PredefinedType:n?|00000000000
IfcConstructionProductResourceType|IfcConstructionResourceType|PredefinedType:n|000000000000
IfcConstructionResource|IfcResource|Usage:e?,BaseCosts:E?,BaseQuantity:e?|0000000000|abstract
IfcConstructionResourceType|IfcTypeResource|BaseCosts:E?,BaseQuantity:e?|00000000000|abstract
IfcContext|IfcObjectDefinition|ObjectType:s?,LongName:s?,Phase:s?,RepresentationContexts:E?,UnitsInContext:e?|000000000|abstract
IfcContextDependentUnit|IfcNamedUnit|Name:s|000
IfcControl|IfcObject|Identification:s?|000000|abstract
IfcController|IfcDistributionControlElement|PredefinedType:n?|000000000
IfcControllerType|IfcDistributionControlElementType|PredefinedType:n|0000000000
IfcConversionBasedUnit|IfcNamedUnit|Name:s,ConversionFactor:e|0000
IfcConversionBasedUnitWithOffset|IfcConversionBasedUnit|ConversionOffset:r|00000
IfcCooledBeam|IfcEnergyConversionDevice|PredefinedType:n?|000000000
IfcCooledBeamType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcCoolingTower|IfcEnergyConversionDevice|PredefinedType:n?|000000000
IfcCoolingTowerType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcCoordinateOperation||SourceCRS:e,TargetCRS:e|00|abstract
IfcCoordinateReferenceSystem||Name:s,Description:s?,GeodeticDatum:s?,VerticalDatum:s?|0000|abstract
IfcCostItem|IfcControl|PredefinedType:n?,CostValues:E?,CostQuantities:E?|000000000
IfcCostSchedule|IfcControl|PredefinedType:n?,Status:s?,SubmittedOn:s?,UpdateDate:s?|0000000000
IfcCostValue|IfcAppliedValue||0000000000
IfcCovering|IfcBuildingElement|PredefinedType:n?|000000000
IfcCoveringType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcCrewResource|IfcConstructionResource|PredefinedType:n?|00000000000
IfcCrewResourceType|IfcConstructionResourceType|PredefinedType:n|000000000000
IfcCsgPrimitive3D|IfcGeometricRepresentationItem|Position:e|0|abstract
IfcCsgSolid|IfcSolidModel|TreeRootExpression:e|0
IfcCurrencyRelationship|IfcResourceLevelRelationship|RelatingMonetaryUnit:e,RelatedMonetaryUnit:e,ExchangeRate:r,RateDateTime:s?,RateSource:e?|0000000
IfcCurtainWall|IfcBuildingElement|PredefinedType:n?|000000000
IfcCurtainWallType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcCurve|IfcGeometricRepresentationItem|||abstract
IfcCurveBoundedPlane|IfcBoundedSurface|BasisSurface:e,OuterBoundary:e,InnerBoundaries:E|000
IfcCurveBoundedSurface|IfcBoundedSurface|BasisSurface:e,Boundaries:E,ImplicitOuter:b|000
IfcCurveStyle|IfcPresentationStyle|CurveFont:e?,CurveWidth:v?,CurveColour:e?,ModelOrDraughting:b?|00000
IfcCurveStyleFont|IfcPresentationItem|Name:s?,PatternList:E|00
IfcCurveStyleFontAndScaling|IfcPresentationItem|Name:s?,CurveFont:e,CurveFontScaling:r|000
IfcCurveStyleFontPattern|IfcPresentationItem|VisibleSegmentLength:r,InvisibleSegmentLength:r|00
IfcCylindricalSurface|IfcElementarySurface|Radius:r|00
IfcDamper|IfcFlowController|PredefinedType:n?|000000000
IfcDamperType|IfcFlowControllerType|PredefinedType:n|0000000000
IfcDerivedProfileDef|IfcProfileDef|ParentProfile:e,Operator:e,Label:s?|00000
IfcDerivedUnit||Elements:E,UnitType:n,UserDefinedType:s?|000
IfcDerivedUnitElement||Unit:e,Exponent:i|00
IfcDimensionalExponents||LengthExponent:i,MassExponent:i,TimeExponent:i,ElectricCurrentExponent:i,ThermodynamicTemperatureExponent:i,AmountOfSubstanceExponent:i,LuminousIntensityExponent:i|0000000
IfcDirection|IfcGeometricRepresentationItem|DirectionRatios:Lr|0
IfcDiscreteAccessory|IfcElementComponent|PredefinedType:n?|000000000
IfcDiscreteAccessoryType|IfcElementComponentType|PredefinedType:n|0000000000
IfcDistributionChamberElement|IfcDistributionFlowElement|PredefinedType:n?|000000000
IfcDistributionChamberElementType|IfcDistributionFlowElementType|PredefinedType:n|0000000000
IfcDistributionCircuit|IfcDistributionSystem||0000000
IfcDistributionControlElement|IfcDistributionElement||00000000
IfcDistributionControlElementType|IfcDistributionElementType||000000000|abstract
IfcDistributionElement|IfcElement||00000000
IfcDistributionElementType|IfcElementType||000000000
IfcDistributionFlowElement|IfcDistributionElement||00000000
IfcDistributionFlowElementType|IfcDistributionElementType||000000000|abstract
IfcDistributionPort|IfcPort|FlowDirection:n?,PredefinedType:n?,SystemType:n?|0000000000
IfcDistributionSystem|IfcSystem|LongName:s?,PredefinedType:n?|0000000
IfcDocumentInformation|IfcExternalInformation|Identification:s,Name:s,Description:s?,Location:s?,Purpose:s?,IntendedUse:s?,Scope:s?,Revision:s?,DocumentOwner:e?,Editors:E?,CreationTime:s?,LastRevisionTime:s?,ElectronicFormat:s?,ValidFrom:s?,ValidUntil:s?,Confidentiality:n?,Status:n?|00000000000000000
IfcDocumentInformationRelationship|IfcResourceLevelRelationship|RelatingDocument:e,RelatedDocuments:E,RelationshipType:s?|00000
IfcDocumentReference|IfcExternalReference|Description:s?,ReferencedDocument:e?|00000
IfcDoor|IfcBuildingElement|OverallHeight:r?,OverallWidth:r?,PredefinedType:n?,OperationType:n?,UserDefinedOperationType:s?|0000000000000
IfcDoorLiningProperties|IfcPreDefinedPropertySet|LiningDepth:r?,LiningThickness:r?,ThresholdDepth:r?,ThresholdThickness:r?,TransomThickness:r?,TransomOffset:r?,LiningOffset:r?,ThresholdOffset:r?,CasingThickness:r?,CasingDepth:r?,ShapeAspectStyle:e?,LiningToPanelOffsetX:r?,LiningToPanelOffsetY:r?|00000000000000000
IfcDoorPanelProperties|IfcPreDefinedPropertySet|PanelDepth:r?,PanelOperation:n,PanelWidth:r?,PanelPosition:n,ShapeAspectStyle:e?|000000000
IfcDoorStandardCase|IfcDoor||0000000000000
IfcDoorStyle|IfcTypeProduct|OperationType:n,ConstructionType:n,ParameterTakesPrecedence:b,Sizeable:b|000000000000
IfcDoorType|IfcBuildingElementType|PredefinedType:n,OperationType:n,ParameterTakesPrecedence:b?,UserDefinedOperationType:s?|0000000000000
IfcDraughtingPreDefinedColour|IfcPreDefinedColour||0
IfcDraughtingPreDefinedCurveFont|IfcPreDefinedCurveFont||0
IfcDuctFitting|IfcFlowFitting|PredefinedType:n?|000000000
IfcDuctFittingType|IfcFlowFittingType|PredefinedType:n|0000000000
IfcDuctSegment|IfcFlowSegment|PredefinedType:n?|000000000
IfcDuctSegmentType|IfcFlowSegmentType|PredefinedType:n|0000000000
IfcDuctSilencer|IfcFlowTreatmentDevice|PredefinedType:n?|000000000
IfcDuctSilencerType|IfcFlowTreatmentDeviceType|PredefinedType:n|0000000000
IfcEdge|IfcTopologicalRepresentationItem|EdgeStart:e,EdgeEnd:e|00
IfcEdgeCurve|IfcEdge|EdgeGeometry:e,SameSense:b|0000
IfcEdgeLoop|IfcLoop|EdgeList:E|0
IfcElectricAppliance|IfcFlowTerminal|PredefinedType:n?|000000000
IfcElectricApplianceType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcElectricDistributionBoard|IfcFlowController|PredefinedType:n?|000000000
IfcElectricDistributionBoardType|IfcFlowControllerType|PredefinedType:n|0000000000
IfcElectricFlowStorageDevice|IfcFlowStorageDevice|PredefinedType:n?|000000000
IfcElectricFlowStorageDeviceType|IfcFlowStorageDeviceType|PredefinedType:n|0000000000
IfcElectricGenerator|IfcEnergyConversionDevice|PredefinedType:n?|000000000
IfcElectricGeneratorType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcElectricMotor|IfcEnergyConversionDevice|PredefinedType:n?|000000000
IfcElectricMotorType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcElectricTimeControl|IfcFlowController|PredefinedType:n?|000000000
IfcElectricTimeControlType|IfcFlowControllerType|PredefinedType:n|0000000000
IfcElement|IfcProduct|Tag:s?|00000000|abstract
IfcElementAssembly|IfcElement|AssemblyPlace:n?,PredefinedType:n?|0000000000
IfcElementAssemblyType|IfcElementType|PredefinedType:n|0000000000
IfcElementComponent|IfcElement||00000000|abstract
IfcElementComponentType|IfcElementType||000000000|abstract
IfcElementQuantity|IfcQuantitySet|MethodOfMeasurement:s?,Quantities:E|000000
IfcElementType|IfcTypeProduct|ElementType:s?|000000000|abstract
IfcElementarySurface|IfcSurface|Position:e|0|abstract
IfcEllipse|IfcConic|SemiAxis1:r,SemiAxis2:r|000
IfcEllipseProfileDef|IfcParameterizedProfileDef|SemiAxis1:r,SemiAxis2:r|00000
IfcEnergyConversionDevice|IfcDistributionFlowElement||00000000
IfcEnergyConversionDeviceType|IfcDistributionFlowElementType||000000000|abstract
IfcEngine|IfcEnergyConversionDevice|PredefinedType:n?|000000000
IfcEngineType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcEvaporativeCooler|IfcEnergyConversionDevice|PredefinedType:n?|000000000
IfcEvaporativeCoolerType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcEvaporator|IfcEnergyConversionDevice|PredefinedType:n?|000000000
IfcEvaporatorType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcEvent|IfcProcess|PredefinedType:n?,EventTriggerType:n?,UserDefinedEventTriggerType:s?,EventOccurenceTime:e?|00000000000
IfcEventTime|IfcSchedulingTime|ActualDate:s?,EarlyDate:s?,LateDate:s?,ScheduleDate:s?|0000000
IfcEventType|IfcTypeProcess|PredefinedType:n,EventTriggerType:n,UserDefinedEventTriggerType:s?|000000000000
IfcExtendedProperties|IfcPropertyAbstraction|Name:s?,Description:s?,Properties:E|000|abstract
IfcExternalInformation||||abstract
IfcExternalReference||Location:s?,Identification:s?,Name:s?|000|abstract
IfcExternalReferenceRelationship|IfcResourceLevelRelationship|RelatingReference:e,RelatedResourceObjects:E|0000
IfcExternalSpatialElement|IfcExternalSpatialStructureElement|PredefinedType:n?|000000000
IfcExternalSpatialStructureElement|IfcSpatialElement||00000000|abstract
IfcExternallyDefinedHatchStyle|IfcExternalReference||000
IfcExternallyDefinedSurfaceStyle|IfcExternalReference||000
IfcExternallyDefinedTextFont|IfcExternalReference||000
IfcExtrudedAreaSolid|IfcSweptAreaSolid|ExtrudedDirection:e,Depth:r|0000
IfcExtrudedAreaSolidTapered|IfcExtrudedAreaSolid|EndSweptArea:e|00000
IfcFace|IfcTopologicalRepresentationItem|Bounds:E|0
IfcFaceBasedSurfaceModel|IfcGeometricRepresentationItem|FbsmFaces:E|0
IfcFaceBound|IfcTopologicalRepresentationItem|Bound:e,Orientation:b|00
IfcFaceOuterBound|IfcFaceBound||00
IfcFaceSurface|IfcFace|FaceSurface:e,SameSense:b|000
IfcFacetedBrep|IfcManifoldSolidBrep||0
IfcFacetedBrepWithVoids|IfcFacetedBrep|Voids:E|00
IfcFailureConnectionCondition|IfcStructuralConnectionCondition|TensionFailureX:r?,TensionFailureY:r?,TensionFailureZ:r?,CompressionFailureX:r?,CompressionFailureY:r?,CompressionFailureZ:r?|0000000
IfcFan|IfcFlowMovingDevice|PredefinedType:n?|000000000
IfcFanType|IfcFlowMovingDeviceType|PredefinedType:n|0000000000
IfcFastener|IfcElementComponent|PredefinedType:n?|000000000
IfcFastenerType|IfcElementComponentType|PredefinedType:n|0000000000
IfcFeatureElement|IfcElement||00000000|abstract
IfcFeatureElementAddition|IfcFeatureElement||00000000|abstract
IfcFeatureElementSubtraction|IfcFeatureElement||00000000|abstract
IfcFillAreaStyle|IfcPresentationStyle|FillStyles:E,ModelorDraughting:b?|000
IfcFillAreaStyleHatching|IfcGeometricRepresentationItem|HatchLineAppearance:e,StartOfNextHatchLine:v,PointOfReferenceHatchLine:e?,PatternStart:e?,HatchLineAngle:r|00000
IfcFillAreaStyleTiles|IfcGeometricRepresentationItem|TilingPattern:E,Tiles:E,TilingScale:r|000
IfcFilter|IfcFlowTreatmentDevice|PredefinedType:n?|000000000
IfcFilterType|IfcFlowTreatmentDeviceType|PredefinedType:n|0000000000
IfcFireSuppressionTerminal|IfcFlowTerminal|PredefinedType:n?|000000000
IfcFireSuppressionTerminalType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcFixedReferenceSweptAreaSolid|IfcSweptAreaSolid|Directrix:e,StartParam:r?,EndParam:r?,FixedReference:e|000000
IfcFlowController|IfcDistributionFlowElement||00000000
IfcFlowControllerType|IfcDistributionFlowElementType||000000000|abstract
IfcFlowFitting|IfcDistributionFlowElement||00000000
IfcFlowFittingType|IfcDistributionFlowElementType||000000000|abstract
IfcFlowInstrument|IfcDistributionControlElement|PredefinedType:n?|000000000
IfcFlowInstrumentType|IfcDistributionControlElementType|PredefinedType:n|0000000000
IfcFlowMeter|IfcFlowController|PredefinedType:n?|000000000
IfcFlowMeterType|IfcFlowControllerType|PredefinedType:n|0000000000
IfcFlowMovingDevice|IfcDistributionFlowElement||00000000
IfcFlowMovingDeviceType|IfcDistributionFlowElementType||000000000|abstract
IfcFlowSegment|IfcDistributionFlowElement||00000000
IfcFlowSegmentType|IfcDistributionFlowElementType||000000000|abstract
IfcFlowStorageDevice|IfcDistributionFlowElement||00000000
IfcFlowStorageDeviceType|IfcDistributionFlowElementType||000000000|abstract
IfcFlowTerminal|IfcDistributionFlowElement||00000000
IfcFlowTerminalType|IfcDistributionFlowElementType||000000000|abstract
IfcFlowTreatmentDevice|IfcDistributionFlowElement||00000000
IfcFlowTreatmentDeviceType|IfcDistributionFlowElementType||000000000|abstract
IfcFooting|IfcBuildingElement|PredefinedType:n?|000000000
IfcFootingType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcFurnishingElement|IfcElement||00000000
IfcFurnishingElementType|IfcElementType||000000000
IfcFurniture|IfcFurnishingElement|PredefinedType:n?|000000000
IfcFurnitureType|IfcFurnishingElementType|AssemblyPlace:n,PredefinedType:n?|00000000000
IfcGeographicElement|IfcElement|PredefinedType:n?|000000000
IfcGeographicElementType|IfcElementType|PredefinedType:n|0000000000
IfcGeometricCurveSet|IfcGeometricSet||0
IfcGeometricRepresentationContext|IfcRepresentationContext|CoordinateSpaceDimension:i,Precision:r?,WorldCoordinateSystem:e,TrueNorth:e?|000000
IfcGeometricRepresentationItem|IfcRepresentationItem|||abstract
IfcGeometricRepresentationSubContext|IfcGeometricRepresentationContext|ParentContext:e,TargetScale:r?,TargetView:n,UserDefinedTargetView:s?|0011110000
IfcGeometricSet|IfcGeometricRepresentationItem|Elements:E|0
IfcGrid|IfcProduct|UAxes:E,VAxes:E,WAxes:E?,PredefinedType:n?|00000000000
IfcGridAxis||AxisTag:s?,AxisCurve:e,SameSense:b|000
IfcGridPlacement|IfcObjectPlacement|PlacementLocation:e,PlacementRefDirection:e?|00
IfcGroup|IfcObject||00000
IfcHalfSpaceSolid|IfcGeometricRepresentationItem|BaseSurface:e,AgreementFlag:b|00
IfcHeatExchanger|IfcEnergyConversionDevice|PredefinedType:n?|000000000
IfcHeatExchangerType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcHumidifier|IfcEnergyConversionDevice|PredefinedType:n?|000000000
IfcHumidifierType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcIShapeProfileDef|IfcParameterizedProfileDef|OverallWidth:r,OverallDepth:r,WebThickness:r,FlangeThickness:r,FilletRadius:r?,FlangeEdgeRadius:r?,FlangeSlope:r?|0000000000
IfcImageTexture|IfcSurfaceTexture|URLReference:s|000000
IfcIndexedColourMap|IfcPresentationItem|MappedTo:e,Opacity:r?,Colours:e,ColourIndex:Li|0000
IfcIndexedPolyCurve|IfcBoundedCurve|Points:e,Segments:E?,SelfIntersect:b?|000
IfcIndexedPolygonalFace|IfcTessellatedItem|CoordIndex:Li|0
IfcIndexedPolygonalFaceWithVoids|IfcIndexedPolygonalFace|InnerCoordIndices:Mi|00
IfcIndexedTextureMap|IfcTextureCoordinate|MappedTo:e,TexCoords:e|000|abstract
IfcIndexedTriangleTextureMap|IfcIndexedTextureMap|TexCoordIndex:Mi?|0000
IfcInterceptor|IfcFlowTreatmentDevice|PredefinedType:n?|000000000
IfcInterceptorType|IfcFlowTreatmentDeviceType|PredefinedType:n|0000000000
IfcIntersectionCurve|IfcSurfaceCurve||000
IfcInventory|IfcGroup|PredefinedType:n?,Jurisdiction:e?,ResponsiblePersons:E?,LastUpdateDate:s?,CurrentValue:e?,OriginalValue:e?|00000000000
IfcIrregularTimeSeries|IfcTimeSeries|Values:E|000000000
IfcIrregularTimeSeriesValue||TimeStamp:s,ListValues:E|00
IfcJunctionBox|IfcFlowFitting|PredefinedType:n?|000000000
IfcJunctionBoxType|IfcFlowFittingType|PredefinedType:n|0000000000
IfcLShapeProfileDef|IfcParameterizedProfileDef|Depth:r,Width:r?,Thickness:r,FilletRadius:r?,EdgeRadius:r?,LegSlope:r?|000000000
IfcLaborResource|IfcConstructionResource|PredefinedType:n?|00000000000
IfcLaborResourceType|IfcConstructionResourceType|PredefinedType:n|000000000000
IfcLagTime|IfcSchedulingTime|LagValue:v,DurationType:n|00000
IfcLamp|IfcFlowTerminal|PredefinedType:n?|000000000
IfcLampType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcLibraryInformation|IfcExternalInformation|Name:s,Version:s?,Publisher:e?,VersionDate:s?,Location:s?,Description:s?|000000
IfcLibraryReference|IfcExternalReference|Description:s?,Language:s?,ReferencedLibrary:e?|000000
IfcLightDistributionData||MainPlaneAngle:r,SecondaryPlaneAngle:Lr,LuminousIntensity:Lr|000
IfcLightFixture|IfcFlowTerminal|PredefinedType:n?|000000000
IfcLightFixtureType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcLightIntensityDistribution||LightDistributionCurve:n,DistributionData:E|00
IfcLightSource|IfcGeometricRepresentationItem|Name:s?,LightColour:e,AmbientIntensity:r?,Intensity:r?|0000|abstract
IfcLightSourceAmbient|IfcLightSource||0000
IfcLightSourceDirectional|IfcLightSource|Orientation:e|00000
IfcLightSourceGoniometric|IfcLightSource|Position:e,ColourAppearance:e?,ColourTemperature:r,LuminousFlux:r,LightEmissionSource:n,LightDistributionDataSource:e|0000000000
IfcLightSourcePositional|IfcLightSource|Position:e,Radius:r,ConstantAttenuation:r,DistanceAttenuation:r,QuadricAttenuation:r|000000000
IfcLightSourceSpot|IfcLightSourcePositional|Orientation:e,ConcentrationExponent:r?,SpreadAngle:r,BeamWidthAngle:r|0000000000000
IfcLine|IfcCurve|Pnt:e,Dir:e|00
IfcLocalPlacement|IfcObjectPlacement|PlacementRelTo:e?,RelativePlacement:e|00
IfcLoop|IfcTopologicalRepresentationItem||
IfcManifoldSolidBrep|IfcSolidModel|Outer:e|0|abstract
IfcMapConversion|IfcCoordinateOperation|Eastings:r,Northings:r,OrthogonalHeight:r,XAxisAbscissa:r?,XAxisOrdinate:r?,Scale:r?|00000000
IfcMappedItem|IfcRepresentationItem|MappingSource:e,MappingTarget:e|00
IfcMaterial|IfcMaterialDefinition|Name:s,Description:s?,Category:s?|000
IfcMaterialClassificationRelationship||MaterialClassifications:E,ClassifiedMaterial:e|00
IfcMaterialConstituent|IfcMaterialDefinition|Name:s?,Description:s?,Material:e,Fraction:r?,Category:s?|00000
IfcMaterialConstituentSet|IfcMaterialDefinition|Name:s?,Description:s?,MaterialConstituents:E?|000
IfcMaterialDefinition||||abstract
IfcMaterialDefinitionRepresentation|IfcProductRepresentation|RepresentedMaterial:e|0000
IfcMaterialLayer|IfcMaterialDefinition|Material:e?,LayerThickness:r,IsVentilated:b?,Name:s?,Description:s?,Category:s?,Priority:i?|0000000
IfcMaterialLayerSet|IfcMaterialDefinition|MaterialLayers:E,LayerSetName:s?,Description:s?|000
IfcMaterialLayerSetUsage|IfcMaterialUsageDefinition|ForLayerSet:e,LayerSetDirection:n,DirectionSense:n,OffsetFromReferenceLine:r,ReferenceExtent:r?|00000
IfcMaterialLayerWithOffsets|IfcMaterialLayer|OffsetDirection:n,OffsetValues:Lr|000000000
IfcMaterialList||Materials:E|0
IfcMaterialProfile|IfcMaterialDefinition|Name:s?,Description:s?,Material:e?,Profile:e,Priority:i?,Category:s?|000000
IfcMaterialProfileSet|IfcMaterialDefinition|Name:s?,Description:s?,MaterialProfiles:E,CompositeProfile:e?|0000
IfcMaterialProfileSetUsage|IfcMaterialUsageDefinition|ForProfileSet:e,CardinalPoint:i?,ReferenceExtent:r?|000
IfcMaterialProfileSetUsageTapering|IfcMaterialProfileSetUsage|ForProfileEndSet:e,CardinalEndPoint:i?|00000
IfcMaterialProfileWithOffsets|IfcMaterialProfile|OffsetValues:Lr|0000000
IfcMaterialProperties|IfcExtendedProperties|Material:e|0000
IfcMaterialRelationship|IfcResourceLevelRelationship|RelatingMaterial:e,RelatedMaterials:E,Expression:s?|00000
IfcMaterialUsageDefinition||||abstract
IfcMeasureWithUnit||ValueComponent:v,UnitComponent:e|00
IfcMechanicalFastener|IfcElementComponent|NominalDiameter:r?,NominalLength:r?,PredefinedType:n?|00000000000
IfcMechanicalFastenerType|IfcElementComponentType|PredefinedType:n,NominalDiameter:r?,NominalLength:r?|000000000000
IfcMedicalDevice|IfcFlowTerminal|PredefinedType:n?|000000000
IfcMedicalDeviceType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcMember|IfcBuildingElement|PredefinedType:n?|000000000
IfcMemberStandardCase|IfcMember||000000000
IfcMemberType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcMetric|IfcConstraint|Benchmark:n,ValueSource:s?,DataValue:v?,ReferencePath:e?|00000000000
IfcMirroredProfileDef|IfcDerivedProfileDef||00010
IfcMonetaryUnit||Currency:s|0
IfcMotorConnection|IfcEnergyConversionDevice|PredefinedType:n?|000000000
IfcMotorConnectionType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcNamedUnit||Dimensions:e,UnitType:n|00|abstract
IfcObject|IfcObjectDefinition|ObjectType:s?|00000|abstract
IfcObjectDefinition|IfcRoot||0000|abstract
IfcObjectPlacement||||abstract
IfcObjective|IfcConstraint|BenchmarkValues:E?,LogicalAggregator:n?,ObjectiveQualifier:n,UserDefinedQualifier:s?|00000000000
IfcOccupant|IfcActor|PredefinedType:n?|0000000
IfcOffsetCurve2D|IfcCurve|BasisCurve:e,Distance:r,SelfIntersect:b|000
IfcOffsetCurve3D|IfcCurve|BasisCurve:e,Distance:r,SelfIntersect:b,RefDirection:e|0000
IfcOpenShell|IfcConnectedFaceSet||0
IfcOpeningElement|IfcFeatureElementSubtraction|PredefinedType:n?|000000000
IfcOpeningStandardCase|IfcOpeningElement||000000000
IfcOrganization||Identification:s?,Name:s,Description:s?,Roles:E?,Addresses:E?|00000
IfcOrganizationRelationship|IfcResourceLevelRelationship|RelatingOrganization:e,RelatedOrganizations:E|0000
IfcOrientedEdge|IfcEdge|EdgeElement:e,Orientation:b|1100
IfcOuterBoundaryCurve|IfcBoundaryCurve||00
IfcOutlet|IfcFlowTerminal|PredefinedType:n?|000000000
IfcOutletType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcOwnerHistory||OwningUser:e,OwningApplication:e,State:n?,ChangeAction:n?,LastModifiedDate:i?,LastModifyingUser:e?,LastModifyingApplication:e?,CreationDate:i|00000000
IfcParameterizedProfileDef|IfcProfileDef|Position:e?|000|abstract
IfcPath|IfcTopologicalRepresentationItem|EdgeList:E|0
IfcPcurve|IfcCurve|BasisSurface:e,ReferenceCurve:e|00
IfcPerformanceHistory|IfcControl|LifeCyclePhase:s,PredefinedType:n?|00000000
IfcPermeableCoveringProperties|IfcPreDefinedPropertySet|OperationType:n,PanelPosition:n,FrameDepth:r?,FrameThickness:r?,ShapeAspectStyle:e?|000000000
IfcPermit|IfcControl|PredefinedType:n?,Status:s?,LongDescription:s?|000000000
IfcPerson||Identification:s?,FamilyName:s?,GivenName:s?,MiddleNames:Ls?,PrefixTitles:Ls?,SuffixTitles:Ls?,Roles:E?,Addresses:E?|00000000
IfcPersonAndOrganization||ThePerson:e,TheOrganization:e,Roles:E?|000
IfcPhysicalComplexQuantity|IfcPhysicalQuantity|HasQuantities:E,Discrimination:s,Quality:s?,Usage:s?|000000
IfcPhysicalQuantity||Name:s,Description:s?|00|abstract
IfcPhysicalSimpleQuantity|IfcPhysicalQuantity|Unit:e?|000|abstract
IfcPile|IfcBuildingElement|PredefinedType:n?,ConstructionType:n?|0000000000
IfcPileType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcPipeFitting|IfcFlowFitting|PredefinedType:n?|000000000
IfcPipeFittingType|IfcFlowFittingType|PredefinedType:n|0000000000
IfcPipeSegment|IfcFlowSegment|PredefinedType:n?|000000000
IfcPipeSegmentType|IfcFlowSegmentType|PredefinedType:n|0000000000
IfcPixelTexture|IfcSurfaceTexture|Width:i,Height:i,ColourComponents:i,Pixel:Lx|000000000
IfcPlacement|IfcGeometricRepresentationItem|Location:e|0|abstract
IfcPlanarBox|IfcPlanarExtent|Placement:e|000
IfcPlanarExtent|IfcGeometricRepresentationItem|SizeInX:r,SizeInY:r|00
IfcPlane|IfcElementarySurface||0
IfcPlate|IfcBuildingElement|PredefinedType:n?|000000000
IfcPlateStandardCase|IfcPlate||000000000
IfcPlateType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcPoint|IfcGeometricRepresentationItem|||abstract
IfcPointOnCurve|IfcPoint|BasisCurve:e,PointParameter:r|00
IfcPointOnSurface|IfcPoint|BasisSurface:e,PointParameterU:r,PointParameterV:r|000
IfcPolyLoop|IfcLoop|Polygon:E|0
IfcPolygonalBoundedHalfSpace|IfcHalfSpaceSolid|Position:e,PolygonalBoundary:e|0000
IfcPolygonalFaceSet|IfcTessellatedFaceSet|Closed:b?,Faces:E,PnIndex:Li?|0000
IfcPolyline|IfcBoundedCurve|Points:E|0
IfcPort|IfcProduct||0000000|abstract
IfcPostalAddress|IfcAddress|InternalLocation:s?,AddressLines:Ls?,PostalBox:s?,Town:s?,Region:s?,PostalCode:s?,Country:s?|0000000000
IfcPreDefinedColour|IfcPreDefinedItem||0|abstract
IfcPreDefinedCurveFont|IfcPreDefinedItem||0|abstract
IfcPreDefinedItem|IfcPresentationItem|Name:s|0|abstract
IfcPreDefinedProperties|IfcPropertyAbstraction|||abstract
IfcPreDefinedPropertySet|IfcPropertySetDefinition||0000|abstract
IfcPreDefinedTextFont|IfcPreDefinedItem||0|abstract
IfcPresentationItem||||abstract
IfcPresentationLayerAssignment||Name:s,Description:s?,AssignedItems:E,Identifier:s?|0000
IfcPresentationLayerWithStyle|IfcPresentationLayerAssignment|LayerOn:b,LayerFrozen:b,LayerBlocked:b,LayerStyles:E|00000000
IfcPresentationStyle||Name:s?|0|abstract
IfcPresentationStyleAssignment||Styles:E|0
IfcProcedure|IfcProcess|PredefinedType:n?|00000000
IfcProcedureType|IfcTypeProcess|PredefinedType:n|0000000000
IfcProcess|IfcObject|Identification:s?,LongDescription:s?|0000000|abstract
IfcProduct|IfcObject|ObjectPlacement:e?,Representation:e?|0000000|abstract
IfcProductDefinitionShape|IfcProductRepresentation||000
IfcProductRepresentation||Name:s?,Description:s?,Representations:E|000|abstract
IfcProfileDef||ProfileType:n,ProfileName:s?|00
IfcProfileProperties|IfcExtendedProperties|ProfileDefinition:e|0000
IfcProject|IfcContext||000000000
IfcProjectLibrary|IfcContext||000000000
IfcProjectOrder|IfcControl|PredefinedType:n?,Status:s?,LongDescription:s?|000000000
IfcProjectedCRS|IfcCoordinateReferenceSystem|MapProjection:s?,MapZone:s?,MapUnit:e?|0000000
IfcProjectionElement|IfcFeatureElementAddition|PredefinedType:n?|000000000
IfcProperty|IfcPropertyAbstraction|Name:s,Description:s?|00|abstract
IfcPropertyAbstraction||||abstract
IfcPropertyBoundedValue|IfcSimpleProperty|UpperBoundValue:v?,LowerBoundValue:v?,Unit:e?,SetPointValue:v?|000000
IfcPropertyDefinition|IfcRoot||0000|abstract
IfcPropertyDependencyRelationship|IfcResourceLevelRelationship|DependingProperty:e,DependantProperty:e,Expression:s?|00000
IfcPropertyEnumeratedValue|IfcSimpleProperty|EnumerationValues:E?,EnumerationReference:e?|0000
IfcPropertyEnumeration|IfcPropertyAbstraction|Name:s,EnumerationValues:E,Unit:e?|000
IfcPropertyListValue|IfcSimpleProperty|ListValues:E?,Unit:e?|0000
IfcPropertyReferenceValue|IfcSimpleProperty|UsageName:s?,PropertyReference:e?|0000
IfcPropertySet|IfcPropertySetDefinition|HasProperties:E|00000
IfcPropertySetDefinition|IfcPropertyDefinition||0000|abstract
IfcPropertySetTemplate|IfcPropertyTemplateDefinition|TemplateType:n?,ApplicableEntity:s?,HasPropertyTemplates:E|0000000
IfcPropertySingleValue|IfcSimpleProperty|NominalValue:v?,Unit:e?|0000
IfcPropertyTableValue|IfcSimpleProperty|DefiningValues:E?,DefinedValues:E?,Expression:s?,DefiningUnit:e?,DefinedUnit:e?,CurveInterpolation:n?|00000000
IfcPropertyTemplate|IfcPropertyTemplateDefinition||0000|abstract
IfcPropertyTemplateDefinition|IfcPropertyDefinition||0000|abstract
IfcProtectiveDevice|IfcFlowController|PredefinedType:n?|000000000
IfcProtectiveDeviceTrippingUnit|IfcDistributionControlElement|PredefinedType:n?|000000000
IfcProtectiveDeviceTrippingUnitType|IfcDistributionControlElementType|PredefinedType:n|0000000000
IfcProtectiveDeviceType|IfcFlowControllerType|PredefinedType:n|0000000000
IfcProxy|IfcProduct|ProxyType:n,Tag:s?|000000000
IfcPump|IfcFlowMovingDevice|PredefinedType:n?|000000000
IfcPumpType|IfcFlowMovingDeviceType|PredefinedType:n|0000000000
IfcQuantityArea|IfcPhysicalSimpleQuantity|AreaValue:r,Formula:s?|00000
IfcQuantityCount|IfcPhysicalSimpleQuantity|CountValue:u,Formula:s?|00000
IfcQuantityLength|IfcPhysicalSimpleQuantity|LengthValue:r,Formula:s?|00000
IfcQuantitySet|IfcPropertySetDefinition||0000|abstract
IfcQuantityTime|IfcPhysicalSimpleQuantity|TimeValue:r,Formula:s?|00000
IfcQuantityVolume|IfcPhysicalSimpleQuantity|VolumeValue:r,Formula:s?|00000
IfcQuantityWeight|IfcPhysicalSimpleQuantity|WeightValue:r,Formula:s?|00000
IfcRailing|IfcBuildingElement|PredefinedType:n?|000000000
IfcRailingType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcRamp|IfcBuildingElement|PredefinedType:n?|000000000
IfcRampFlight|IfcBuildingElement|PredefinedType:n?|000000000
IfcRampFlightType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcRampType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcRationalBSplineCurveWithKnots|IfcBSplineCurveWithKnots|WeightsData:Lr|000000000
IfcRationalBSplineSurfaceWithKnots|IfcBSplineSurfaceWithKnots|WeightsData:Mr|0000000000000
IfcRectangleHollowProfileDef|IfcRectangleProfileDef|WallThickness:r,InnerFilletRadius:r?,OuterFilletRadius:r?|00000000
IfcRectangleProfileDef|IfcParameterizedProfileDef|XDim:r,YDim:r|00000
IfcRectangularPyramid|IfcCsgPrimitive3D|XLength:r,YLength:r,Height:r|0000
IfcRectangularTrimmedSurface|IfcBoundedSurface|BasisSurface:e,U1:r,V1:r,U2:r,V2:r,Usense:b,Vsense:b|0000000
IfcRecurrencePattern||RecurrenceType:n,DayComponent:Li?,WeekdayComponent:Li?,MonthComponent:Li?,Position:i?,Interval:i?,Occurrences:i?,TimePeriods:E?|00000000
IfcReference||TypeIdentifier:s?,AttributeIdentifier:s?,InstanceName:s?,ListPositions:Li?,InnerReference:e?|00000
IfcRegularTimeSeries|IfcTimeSeries|TimeStep:r,Values:E|0000000000
IfcReinforcementBarProperties|IfcPreDefinedProperties|TotalCrossSectionArea:r,SteelGrade:s,BarSurface:n?,EffectiveDepth:r?,NominalBarDiameter:r?,BarCount:u?|000000
IfcReinforcementDefinitionProperties|IfcPreDefinedPropertySet|DefinitionType:s?,ReinforcementSectionDefinitions:E|000000
IfcReinforcingBar|IfcReinforcingElement|NominalDiameter:r?,CrossSectionArea:r?,BarLength:r?,PredefinedType:n?,BarSurface:n?|00000000000000
IfcReinforcingBarType|IfcReinforcingElementType|PredefinedType:n,NominalDiameter:r?,CrossSectionArea:r?,BarLength:r?,BarSurface:n?,BendingShapeCode:s?,BendingParameters:E?|0000000000000000
IfcReinforcingElement|IfcElementComponent|SteelGrade:s?|000000000|abstract
IfcReinforcingElementType|IfcElementComponentType||000000000|abstract
IfcReinforcingMesh|IfcReinforcingElement|MeshLength:r?,MeshWidth:r?,LongitudinalBarNominalDiameter:r?,TransverseBarNominalDiameter:r?,LongitudinalBarCrossSectionArea:r?,TransverseBarCrossSectionArea:r?,LongitudinalBarSpacing:r?,TransverseBarSpacing:r?,PredefinedType:n?|000000000000000000
IfcReinforcingMeshType|IfcReinforcingElementType|PredefinedType:n,MeshLength:r?,MeshWidth:r?,LongitudinalBarNominalDiameter:r?,TransverseBarNominalDiameter:r?,LongitudinalBarCrossSectionArea:r?,TransverseBarCrossSectionArea:r?,LongitudinalBarSpacing:r?,TransverseBarSpacing:r?,BendingShapeCode:s?,BendingParameters:E?|00000000000000000000
IfcRelAggregates|IfcRelDecomposes|RelatingObject:e,RelatedObjects:E|000000
IfcRelAssigns|IfcRelationship|RelatedObjects:E,RelatedObjectsType:n?|000000|abstract
IfcRelAssignsToActor|IfcRelAssigns|RelatingActor:e,ActingRole:e?|00000000
IfcRelAssignsToControl|IfcRelAssigns|RelatingControl:e|0000000
IfcRelAssignsToGroup|IfcRelAssigns|RelatingGroup:e|0000000
IfcRelAssignsToGroupByFactor|IfcRelAssignsToGroup|Factor:r|00000000
IfcRelAssignsToProcess|IfcRelAssigns|RelatingProcess:e,QuantityInProcess:e?|00000000
IfcRelAssignsToProduct|IfcRelAssigns|RelatingProduct:e|0000000
IfcRelAssignsToResource|IfcRelAssigns|RelatingResource:e|0000000
IfcRelAssociates|IfcRelationship|RelatedObjects:E|00000|abstract
IfcRelAssociatesApproval|IfcRelAssociates|RelatingApproval:e|000000
IfcRelAssociatesClassification|IfcRelAssociates|RelatingClassification:e|000000
IfcRelAssociatesConstraint|IfcRelAssociates|Intent:s?,RelatingConstraint:e|0000000
IfcRelAssociatesDocument|IfcRelAssociates|RelatingDocument:e|000000
IfcRelAssociatesLibrary|IfcRelAssociates|RelatingLibrary:e|000000
IfcRelAssociatesMaterial|IfcRelAssociates|RelatingMaterial:e|000000
IfcRelConnects|IfcRelationship||0000|abstract
IfcRelConnectsElements|IfcRelConnects|ConnectionGeometry:e?,RelatingElement:e,RelatedElement:e|0000000
IfcRelConnectsPathElements|IfcRelConnectsElements|RelatingPriorities:Li,RelatedPriorities:Li,RelatedConnectionType:n,RelatingConnectionType:n|00000000000
IfcRelConnectsPortToElement|IfcRelConnects|RelatingPort:e,RelatedElement:e|000000
IfcRelConnectsPorts|IfcRelConnects|RelatingPort:e,RelatedPort:e,RealizingElement:e?|0000000
IfcRelConnectsStructuralActivity|IfcRelConnects|RelatingElement:e,RelatedStructuralActivity:e|000000
IfcRelConnectsStructuralMember|IfcRelConnects|RelatingStructuralMember:e,RelatedStructuralConnection:e,AppliedCondition:e?,AdditionalConditions:e?,SupportedLength:r?,ConditionCoordinateSystem:e?|0000000000
IfcRelConnectsWithEccentricity|IfcRelConnectsStructuralMember|ConnectionConstraint:e|00000000000
IfcRelConnectsWithRealizingElements|IfcRelConnectsElements|RealizingElements:E,ConnectionType:s?|000000000
IfcRelContainedInSpatialStructure|IfcRelConnects|RelatedElements:E,RelatingStructure:e|000000
IfcRelCoversBldgElements|IfcRelConnects|RelatingBuildingElement:e,RelatedCoverings:E|000000
IfcRelCoversSpaces|IfcRelConnects|RelatingSpace:e,RelatedCoverings:E|000000
IfcRelDeclares|IfcRelationship|RelatingContext:e,RelatedDefinitions:E|000000
IfcRelDecomposes|IfcRelationship||0000|abstract
IfcRelDefines|IfcRelationship||0000|abstract
IfcRelDefinesByObject|IfcRelDefines|RelatedObjects:E,RelatingObject:e|000000
IfcRelDefinesByProperties|IfcRelDefines|RelatedObjects:E,RelatingPropertyDefinition:v|000000
IfcRelDefinesByTemplate|IfcRelDefines|RelatedPropertySets:E,RelatingTemplate:e|000000
IfcRelDefinesByType|IfcRelDefines|RelatedObjects:E,RelatingType:e|000000
IfcRelFillsElement|IfcRelConnects|RelatingOpeningElement:e,RelatedBuildingElement:e|000000
IfcRelFlowControlElements|IfcRelConnects|RelatedControlElements:E,RelatingFlowElement:e|000000
IfcRelInterferesElements|IfcRelConnects|RelatingElement:e,RelatedElement:e,InterferenceGeometry:e?,InterferenceType:s?,ImpliedOrder:b|000000000
IfcRelNests|IfcRelDecomposes|RelatingObject:e,RelatedObjects:E|000000
IfcRelProjectsElement|IfcRelDecomposes|RelatingElement:e,RelatedFeatureElement:e|000000
IfcRelReferencedInSpatialStructure|IfcRelConnects|RelatedElements:E,RelatingStructure:e|000000
IfcRelSequence|IfcRelConnects|RelatingProcess:e,RelatedProcess:e,TimeLag:e?,SequenceType:n?,UserDefinedSequenceType:s?|000000000
IfcRelServicesBuildings|IfcRelConnects|RelatingSystem:e,RelatedBuildings:E|000000
IfcRelSpaceBoundary|IfcRelConnects|RelatingSpace:e,RelatedBuildingElement:e,ConnectionGeometry:e?,PhysicalOrVirtualBoundary:n,InternalOrExternalBoundary:n|000000000
IfcRelSpaceBoundary1stLevel|IfcRelSpaceBoundary|ParentBoundary:e?|0000000000
IfcRelSpaceBoundary2ndLevel|IfcRelSpaceBoundary1stLevel|CorrespondingBoundary:e?|00000000000
IfcRelVoidsElement|IfcRelDecomposes|RelatingBuildingElement:e,RelatedOpeningElement:e|000000
IfcRelationship|IfcRoot||0000|abstract
IfcReparametrisedCompositeCurveSegment|IfcCompositeCurveSegment|ParamLength:r|0000
IfcRepresentation||ContextOfItems:e,RepresentationIdentifier:s?,RepresentationType:s?,Items:E|0000|abstract
IfcRepresentationContext||ContextIdentifier:s?,ContextType:s?|00|abstract
IfcRepresentationItem||||abstract
IfcRepresentationMap||MappingOrigin:e,MappedRepresentation:e|00
IfcResource|IfcObject|Identification:s?,LongDescription:s?|0000000|abstract
IfcResourceApprovalRelationship|IfcResourceLevelRelationship|RelatedResourceObjects:E,RelatingApproval:e|0000
IfcResourceConstraintRelationship|IfcResourceLevelRelationship|RelatingConstraint:e,RelatedResourceObjects:E|0000
IfcResourceLevelRelationship||Name:s?,Description:s?|00|abstract
IfcResourceTime|IfcSchedulingTime|ScheduleWork:s?,ScheduleUsage:r?,ScheduleStart:s?,ScheduleFinish:s?,ScheduleContour:s?,LevelingDelay:s?,IsOverAllocated:b?,StatusTime:s?,ActualWork:s?,ActualUsage:r?,ActualStart:s?,ActualFinish:s?,RemainingWork:s?,RemainingUsage:r?,Completion:r?|000000000000000000
IfcRevolvedAreaSolid|IfcSweptAreaSolid|Axis:e,Angle:r|0000
IfcRevolvedAreaSolidTapered|IfcRevolvedAreaSolid|EndSweptArea:e|00000
IfcRightCircularCone|IfcCsgPrimitive3D|Height:r,BottomRadius:r|000
IfcRightCircularCylinder|IfcCsgPrimitive3D|Height:r,Radius:r|000
IfcRoof|IfcBuildingElement|PredefinedType:n?|000000000
IfcRoofType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcRoot||GlobalId:s,OwnerHistory:e?,Name:s?,Description:s?|0000|abstract
IfcRoundedRectangleProfileDef|IfcRectangleProfileDef|RoundingRadius:r|000000
IfcSIUnit|IfcNamedUnit|Prefix:n?,Name:n|1000
IfcSanitaryTerminal|IfcFlowTerminal|PredefinedType:n?|000000000
IfcSanitaryTerminalType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcSchedulingTime||Name:s?,DataOrigin:n?,UserDefinedDataOrigin:s?|000|abstract
IfcSeamCurve|IfcSurfaceCurve||000
IfcSectionProperties|IfcPreDefinedProperties|SectionType:n,StartProfile:e,EndProfile:e?|000
IfcSectionReinforcementProperties|IfcPreDefinedProperties|LongitudinalStartPosition:r,LongitudinalEndPosition:r,TransversePosition:r?,ReinforcementRole:n,SectionDefinition:e,CrossSectionReinforcementDefinitions:E|000000
IfcSectionedSpine|IfcGeometricRepresentationItem|SpineCurve:e,CrossSections:E,CrossSectionPositions:E|000
IfcSensor|IfcDistributionControlElement|PredefinedType:n?|000000000
IfcSensorType|IfcDistributionControlElementType|PredefinedType:n|0000000000
IfcShadingDevice|IfcBuildingElement|PredefinedType:n?|000000000
IfcShadingDeviceType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcShapeAspect||ShapeRepresentations:E,Name:s?,Description:s?,ProductDefinitional:b,PartOfProductDefinitionShape:e?|00000
IfcShapeModel|IfcRepresentation||0000|abstract
IfcShapeRepresentation|IfcShapeModel||0000
IfcShellBasedSurfaceModel|IfcGeometricRepresentationItem|SbsmBoundary:E|0
IfcSimpleProperty|IfcProperty||00|abstract
IfcSimplePropertyTemplate|IfcPropertyTemplate|TemplateType:n?,PrimaryMeasureType:s?,SecondaryMeasureType:s?,Enumerators:e?,PrimaryUnit:e?,SecondaryUnit:e?,Expression:s?,AccessState:n?|000000000000
IfcSite|IfcSpatialStructureElement|RefLatitude:Li?,RefLongitude:Li?,RefElevation:r?,LandTitleNumber:s?,SiteAddress:e?|00000000000000
IfcSlab|IfcBuildingElement|PredefinedType:n?|000000000
IfcSlabElementedCase|IfcSlab||000000000
IfcSlabStandardCase|IfcSlab||000000000
IfcSlabType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcSlippageConnectionCondition|IfcStructuralConnectionCondition|SlippageX:r?,SlippageY:r?,SlippageZ:r?|0000
IfcSolarDevice|IfcEnergyConversionDevice|PredefinedType:n?|000000000
IfcSolarDeviceType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcSolidModel|IfcGeometricRepresentationItem|||abstract
IfcSpace|IfcSpatialStructureElement|PredefinedType:n?,ElevationWithFlooring:r?|00000000000
IfcSpaceHeater|IfcFlowTerminal|PredefinedType:n?|000000000
IfcSpaceHeaterType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcSpaceType|IfcSpatialStructureElementType|PredefinedType:n,LongName:s?|00000000000
IfcSpatialElement|IfcProduct|LongName:s?|00000000|abstract
IfcSpatialElementType|IfcTypeProduct|ElementType:s?|000000000|abstract
IfcSpatialStructureElement|IfcSpatialElement|CompositionType:n?|000000000|abstract
IfcSpatialStructureElementType|IfcSpatialElementType||000000000|abstract
IfcSpatialZone|IfcSpatialElement|PredefinedType:n?|000000000
IfcSpatialZoneType|IfcSpatialElementType|PredefinedType:n,LongName:s?|00000000000
IfcSphere|IfcCsgPrimitive3D|Radius:r|00
IfcSphericalSurface|IfcElementarySurface|Radius:r|00
IfcStackTerminal|IfcFlowTerminal|PredefinedType:n?|000000000
IfcStackTerminalType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcStair|IfcBuildingElement|PredefinedType:n?|000000000
IfcStairFlight|IfcBuildingElement|NumberOfRisers:i?,NumberOfTreads:i?,RiserHeight:r?,TreadLength:r?,PredefinedType:n?|0000000000000
IfcStairFlightType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcStairType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcStructuralAction|IfcStructuralActivity|DestabilizingLoad:b?|0000000000|abstract
IfcStructuralActivity|IfcProduct|AppliedLoad:e,GlobalOrLocal:n|000000000|abstract
IfcStructuralAnalysisModel|IfcSystem|PredefinedType:n,OrientationOf2DPlane:e?,LoadedBy:E?,HasResults:E?,SharedPlacement:e?|0000000000
IfcStructuralConnection|IfcStructuralItem|AppliedCondition:e?|00000000|abstract
IfcStructuralConnectionCondition||Name:s?|0|abstract
IfcStructuralCurveAction|IfcStructuralAction|ProjectedOrTrue:n?,PredefinedType:n|000000000000
IfcStructuralCurveConnection|IfcStructuralConnection|Axis:e|000000000
IfcStructuralCurveMember|IfcStructuralMember|PredefinedType:n,Axis:e|000000000
IfcStructuralCurveMemberVarying|IfcStructuralCurveMember||000000000
IfcStructuralCurveReaction|IfcStructuralReaction|PredefinedType:n|0000000000
IfcStructuralItem|IfcProduct||0000000|abstract
IfcStructuralLinearAction|IfcStructuralCurveAction||000000000000
IfcStructuralLoad||Name:s?|0|abstract
IfcStructuralLoadCase|IfcStructuralLoadGroup|SelfWeightCoefficients:Lr?|00000000000
IfcStructuralLoadConfiguration|IfcStructuralLoad|Values:E,Locations:Mr?|000
IfcStructuralLoadGroup|IfcGroup|PredefinedType:n,ActionType:n,ActionSource:n,Coefficient:r?,Purpose:s?|0000000000
IfcStructuralLoadLinearForce|IfcStructuralLoadStatic|LinearForceX:r?,LinearForceY:r?,LinearForceZ:r?,LinearMomentX:r?,LinearMomentY:r?,LinearMomentZ:r?|0000000
IfcStructuralLoadOrResult|IfcStructuralLoad||0|abstract
IfcStructuralLoadPlanarForce|IfcStructuralLoadStatic|PlanarForceX:r?,PlanarForceY:r?,PlanarForceZ:r?|0000
IfcStructuralLoadSingleDisplacement|IfcStructuralLoadStatic|DisplacementX:r?,DisplacementY:r?,DisplacementZ:r?,RotationalDisplacementRX:r?,RotationalDisplacementRY:r?,RotationalDisplacementRZ:r?|0000000
IfcStructuralLoadSingleDisplacementDistortion|IfcStructuralLoadSingleDisplacement|Distortion:r?|00000000
IfcStructuralLoadSingleForce|IfcStructuralLoadStatic|ForceX:r?,ForceY:r?,ForceZ:r?,MomentX:r?,MomentY:r?,MomentZ:r?|0000000
IfcStructuralLoadSingleForceWarping|IfcStructuralLoadSingleForce|WarpingMoment:r?|00000000
IfcStructuralLoadStatic|IfcStructuralLoadOrResult||0|abstract
IfcStructuralLoadTemperature|IfcStructuralLoadStatic|DeltaTConstant:r?,DeltaTY:r?,DeltaTZ:r?|0000
IfcStructuralMember|IfcStructuralItem||0000000|abstract
IfcStructuralPlanarAction|IfcStructuralSurfaceAction||000000000000
IfcStructuralPointAction|IfcStructuralAction||0000000000
IfcStructuralPointConnection|IfcStructuralConnection|ConditionCoordinateSystem:e?|000000000
IfcStructuralPointReaction|IfcStructuralReaction||000000000
IfcStructuralReaction|IfcStructuralActivity||000000000|abstract
IfcStructuralResultGroup|IfcGroup|TheoryType:n,ResultForLoadGroup:e?,IsLinear:b|00000000
IfcStructuralSurfaceAction|IfcStructuralAction|ProjectedOrTrue:n?,PredefinedType:n|000000000000
IfcStructuralSurfaceConnection|IfcStructuralConnection||00000000
IfcStructuralSurfaceMember|IfcStructuralMember|PredefinedType:n,Thickness:r?|000000000
IfcStructuralSurfaceMemberVarying|IfcStructuralSurfaceMember||000000000
IfcStructuralSurfaceReaction|IfcStructuralReaction|PredefinedType:n|0000000000
IfcStyleModel|IfcRepresentation||0000|abstract
IfcStyledItem|IfcRepresentationItem|Item:e?,Styles:E,Name:s?|000
IfcStyledRepresentation|IfcStyleModel||0000
IfcSubContractResource|IfcConstructionResource|PredefinedType:n?|00000000000
IfcSubContractResourceType|IfcConstructionResourceType|PredefinedType:n|000000000000
IfcSubedge|IfcEdge|ParentEdge:e|000
IfcSurface|IfcGeometricRepresentationItem|||abstract
IfcSurfaceCurve|IfcCurve|Curve3D:e,AssociatedGeometry:E,MasterRepresentation:n|000
IfcSurfaceCurveSweptAreaSolid|IfcSweptAreaSolid|Directrix:e,StartParam:r?,EndParam:r?,ReferenceSurface:e|000000
IfcSurfaceFeature|IfcFeatureElement|PredefinedType:n?|000000000
IfcSurfaceOfLinearExtrusion|IfcSweptSurface|ExtrudedDirection:e,Depth:r|0000
IfcSurfaceOfRevolution|IfcSweptSurface|AxisPosition:e|000
IfcSurfaceReinforcementArea|IfcStructuralLoadOrResult|SurfaceReinforcement1:Lr?,SurfaceReinforcement2:Lr?,ShearReinforcement:r?|0000
IfcSurfaceStyle|IfcPresentationStyle|Side:n,Styles:E|000
IfcSurfaceStyleLighting|IfcPresentationItem|DiffuseTransmissionColour:e,DiffuseReflectionColour:e,TransmissionColour:e,ReflectanceColour:e|0000
IfcSurfaceStyleRefraction|IfcPresentationItem|RefractionIndex:r?,DispersionFactor:r?|00
IfcSurfaceStyleRendering|IfcSurfaceStyleShading|DiffuseColour:v?,TransmissionColour:v?,DiffuseTransmissionColour:v?,ReflectionColour:v?,SpecularColour:v?,SpecularHighlight:v?,ReflectanceMethod:n|000000000
IfcSurfaceStyleShading|IfcPresentationItem|SurfaceColour:e,Transparency:r?|00
IfcSurfaceStyleWithTextures|IfcPresentationItem|Textures:E|0
IfcSurfaceTexture|IfcPresentationItem|RepeatS:b,RepeatT:b,Mode:s?,TextureTransform:e?,Parameter:Ls?|00000|abstract
IfcSweptAreaSolid|IfcSolidModel|SweptArea:e,Position:e?|00|abstract
IfcSweptDiskSolid|IfcSolidModel|Directrix:e,Radius:r,InnerRadius:r?,StartParam:r?,EndParam:r?|00000
IfcSweptDiskSolidPolygonal|IfcSweptDiskSolid|FilletRadius:r?|000000
IfcSweptSurface|IfcSurface|SweptCurve:e,Position:e?|00|abstract
IfcSwitchingDevice|IfcFlowController|PredefinedType:n?|000000000
IfcSwitchingDeviceType|IfcFlowControllerType|PredefinedType:n|0000000000
IfcSystem|IfcGroup||00000
IfcSystemFurnitureElement|IfcFurnishingElement|PredefinedType:n?|000000000
IfcSystemFurnitureElementType|IfcFurnishingElementType|PredefinedType:n?|0000000000
IfcTShapeProfileDef|IfcParameterizedProfileDef|Depth:r,FlangeWidth:r,WebThickness:r,FlangeThickness:r,FilletRadius:r?,FlangeEdgeRadius:r?,WebEdgeRadius:r?,WebSlope:r?,FlangeSlope:r?|000000000000
IfcTable||Name:s?,Rows:E?,Columns:E?|000
IfcTableColumn||Identifier:s?,Name:s?,Description:s?,Unit:e?,ReferencePath:e?|00000
IfcTableRow||RowCells:E?,IsHeading:b?|00
IfcTank|IfcFlowStorageDevice|PredefinedType:n?|000000000
IfcTankType|IfcFlowStorageDeviceType|PredefinedType:n|0000000000
IfcTask|IfcProcess|Status:s?,WorkMethod:s?,IsMilestone:b,Priority:i?,TaskTime:e?,PredefinedType:n?|0000000000000
IfcTaskTime|IfcSchedulingTime|DurationType:n?,ScheduleDuration:s?,ScheduleStart:s?,ScheduleFinish:s?,EarlyStart:s?,EarlyFinish:s?,LateStart:s?,LateFinish:s?,FreeFloat:s?,TotalFloat:s?,IsCritical:b?,StatusTime:s?,ActualDuration:s?,ActualStart:s?,ActualFinish:s?,RemainingTime:s?,Completion:r?|00000000000000000000
IfcTaskTimeRecurring|IfcTaskTime|Recurrence:e|000000000000000000000
IfcTaskType|IfcTypeProcess|PredefinedType:n,WorkMethod:s?|00000000000
IfcTelecomAddress|IfcAddress|TelephoneNumbers:Ls?,FacsimileNumbers:Ls?,PagerNumber:s?,ElectronicMailAddresses:Ls?,WWWHomePageURL:s?,MessagingIDs:Ls?|000000000
IfcTendon|IfcReinforcingElement|PredefinedType:n?,NominalDiameter:r?,CrossSectionArea:r?,TensionForce:r?,PreStress:r?,FrictionCoefficient:r?,AnchorageSlip:r?,MinCurvatureRadius:r?|00000000000000000
IfcTendonAnchor|IfcReinforcingElement|PredefinedType:n?|0000000000
IfcTendonAnchorType|IfcReinforcingElementType|PredefinedType:n|0000000000
IfcTendonType|IfcReinforcingElementType|PredefinedType:n,NominalDiameter:r?,CrossSectionArea:r?,SheathDiameter:r?|0000000000000
IfcTessellatedFaceSet|IfcTessellatedItem|Coordinates:e|0|abstract
IfcTessellatedItem|IfcGeometricRepresentationItem|||abstract
IfcTextLiteral|IfcGeometricRepresentationItem|Literal:s,Placement:e,Path:n|000
IfcTextLiteralWithExtent|IfcTextLiteral|Extent:e,BoxAlignment:s|00000
IfcTextStyle|IfcPresentationStyle|TextCharacterAppearance:e?,TextStyle:e?,TextFontStyle:e,ModelOrDraughting:b?|00000
IfcTextStyleFontModel|IfcPreDefinedTextFont|FontFamily:Ls,FontStyle:s?,FontVariant:s?,FontWeight:s?,FontSize:v|000000
IfcTextStyleForDefinedFont|IfcPresentationItem|Colour:e,BackgroundColour:e?|00
IfcTextStyleTextModel|IfcPresentationItem|TextIndent:v?,TextAlign:s?,TextDecoration:s?,LetterSpacing:v?,WordSpacing:v?,TextTransform:s?,LineHeight:v?|0000000
IfcTextureCoordinate|IfcPresentationItem|Maps:E|0|abstract
IfcTextureCoordinateGenerator|IfcTextureCoordinate|Mode:s,Parameter:Lr?|000
IfcTextureMap|IfcTextureCoordinate|Vertices:E,MappedTo:e|000
IfcTextureVertex|IfcPresentationItem|Coordinates:Lr|0
IfcTextureVertexList|IfcPresentationItem|TexCoordsList:Mr|0
IfcTimePeriod||StartTime:s,EndTime:s|00
IfcTimeSeries||Name:s,Description:s?,StartTime:s,EndTime:s,TimeSeriesDataType:n,DataOrigin:n,UserDefinedDataOrigin:s?,Unit:e?|00000000|abstract
IfcTimeSeriesValue||ListValues:E|0
IfcTopologicalRepresentationItem|IfcRepresentationItem|||abstract
IfcTopologyRepresentation|IfcShapeModel||0000
IfcToroidalSurface|IfcElementarySurface|MajorRadius:r,MinorRadius:r|000
IfcTransformer|IfcEnergyConversionDevice|PredefinedType:n?|000000000
IfcTransformerType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcTransportElement|IfcElement|PredefinedType:n?|000000000
IfcTransportElementType|IfcElementType|PredefinedType:n|0000000000
IfcTrapeziumProfileDef|IfcParameterizedProfileDef|BottomXDim:r,TopXDim:r,YDim:r,TopXOffset:r|0000000
IfcTriangulatedFaceSet|IfcTessellatedFaceSet|Normals:Mr?,Closed:b?,CoordIndex:Mi,PnIndex:Li?|00000
IfcTrimmedCurve|IfcBoundedCurve|BasisCurve:e,Trim1:E,Trim2:E,SenseAgreement:b,MasterRepresentation:n|00000
IfcTubeBundle|IfcEnergyConversionDevice|PredefinedType:n?|000000000
IfcTubeBundleType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcTypeObject|IfcObjectDefinition|ApplicableOccurrence:s?,HasPropertySets:E?|000000
IfcTypeProcess|IfcTypeObject|Identification:s?,LongDescription:s?,ProcessType:s?|000000000|abstract
IfcTypeProduct|IfcTypeObject|RepresentationMaps:E?,Tag:s?|00000000
IfcTypeResource|IfcTypeObject|Identification:s?,LongDescription:s?,ResourceType:s?|000000000|abstract
IfcUShapeProfileDef|IfcParameterizedProfileDef|Depth:r,FlangeWidth:r,WebThickness:r,FlangeThickness:r,FilletRadius:r?,EdgeRadius:r?,FlangeSlope:r?|0000000000
IfcUnitAssignment||Units:E|0
IfcUnitaryControlElement|IfcDistributionControlElement|PredefinedType:n?|000000000
IfcUnitaryControlElementType|IfcDistributionControlElementType|PredefinedType:n|0000000000
IfcUnitaryEquipment|IfcEnergyConversionDevice|PredefinedType:n?|000000000
IfcUnitaryEquipmentType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcValve|IfcFlowController|PredefinedType:n?|000000000
IfcValveType|IfcFlowControllerType|PredefinedType:n|0000000000
IfcVector|IfcGeometricRepresentationItem|Orientation:e,Magnitude:r|00
IfcVertex|IfcTopologicalRepresentationItem||
IfcVertexLoop|IfcLoop|LoopVertex:e|0
IfcVertexPoint|IfcVertex|VertexGeometry:e|0
IfcVibrationIsolator|IfcElementComponent|PredefinedType:n?|000000000
IfcVibrationIsolatorType|IfcElementComponentType|PredefinedType:n|0000000000
IfcVirtualElement|IfcElement||00000000
IfcVirtualGridIntersection||IntersectingAxes:E,OffsetDistances:Lr|00
IfcVoidingFeature|IfcFeatureElementSubtraction|PredefinedType:n?|000000000
IfcWall|IfcBuildingElement|PredefinedType:n?|000000000
IfcWallElementedCase|IfcWall||000000000
IfcWallStandardCase|IfcWall||000000000
IfcWallType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcWasteTerminal|IfcFlowTerminal|PredefinedType:n?|000000000
IfcWasteTerminalType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcWindow|IfcBuildingElement|OverallHeight:r?,OverallWidth:r?,PredefinedType:n?,PartitioningType:n?,UserDefinedPartitioningType:s?|0000000000000
IfcWindowLiningProperties|IfcPreDefinedPropertySet|LiningDepth:r?,LiningThickness:r?,TransomThickness:r?,MullionThickness:r?,FirstTransomOffset:r?,SecondTransomOffset:r?,FirstMullionOffset:r?,SecondMullionOffset:r?,ShapeAspectStyle:e?,LiningOffset:r?,LiningToPanelOffsetX:r?,LiningToPanelOffsetY:r?|0000000000000000
IfcWindowPanelProperties|IfcPreDefinedPropertySet|OperationType:n,PanelPosition:n,FrameDepth:r?,FrameThickness:r?,ShapeAspectStyle:e?|000000000
IfcWindowStandardCase|IfcWindow||0000000000000
IfcWindowStyle|IfcTypeProduct|ConstructionType:n,OperationType:n,ParameterTakesPrecedence:b,Sizeable:b|000000000000
IfcWindowType|IfcBuildingElementType|PredefinedType:n,PartitioningType:n,ParameterTakesPrecedence:b?,UserDefinedPartitioningType:s?|0000000000000
IfcWorkCalendar|IfcControl|WorkingTimes:E?,ExceptionTimes:E?,PredefinedType:n?|000000000
IfcWorkControl|IfcControl|CreationDate:s,Creators:E?,Purpose:s?,Duration:s?,TotalFloat:s?,StartTime:s,FinishTime:s?|0000000000000|abstract
IfcWorkPlan|IfcWorkControl|PredefinedType:n?|00000000000000
IfcWorkSchedule|IfcWorkControl|PredefinedType:n?|00000000000000
IfcWorkTime|IfcSchedulingTime|RecurrencePattern:e?,Start:s?,Finish:s?|000000
IfcZShapeProfileDef|IfcParameterizedProfileDef|Depth:r,FlangeWidth:r,WebThickness:r,FlangeThickness:r,FilletRadius:r?,EdgeRadius:r?|000000000
IfcZone|IfcSystem|LongName:s?|000000
"""
    /// Defined types with the kind of their underlying value (typed values in selects, ifcXML "-wrapper" elements).
    static let ifc4Types = "IfcAbsorbedDoseMeasure:r IfcAccelerationMeasure:r IfcAmountOfSubstanceMeasure:r IfcAngularVelocityMeasure:r IfcArcIndex:Li IfcAreaDensityMeasure:r IfcAreaMeasure:r IfcBinary:x IfcBoolean:b IfcBoxAlignment:s IfcCardinalPointReference:i IfcComplexNumber:Lr IfcCompoundPlaneAngleMeasure:Li IfcContextDependentMeasure:r IfcCountMeasure:u IfcCurvatureMeasure:r IfcDate:s IfcDateTime:s IfcDayInMonthNumber:i IfcDayInWeekNumber:i IfcDescriptiveMeasure:s IfcDimensionCount:i IfcDoseEquivalentMeasure:r IfcDuration:s IfcDynamicViscosityMeasure:r IfcElectricCapacitanceMeasure:r IfcElectricChargeMeasure:r IfcElectricConductanceMeasure:r IfcElectricCurrentMeasure:r IfcElectricResistanceMeasure:r IfcElectricVoltageMeasure:r IfcEnergyMeasure:r IfcFontStyle:s IfcFontVariant:s IfcFontWeight:s IfcForceMeasure:r IfcFrequencyMeasure:r IfcGloballyUniqueId:s IfcHeatFluxDensityMeasure:r IfcHeatingValueMeasure:r IfcIdentifier:s IfcIlluminanceMeasure:r IfcInductanceMeasure:r IfcInteger:i IfcIntegerCountRateMeasure:i IfcIonConcentrationMeasure:r IfcIsothermalMoistureCapacityMeasure:r IfcKinematicViscosityMeasure:r IfcLabel:s IfcLanguageId:s IfcLengthMeasure:r IfcLineIndex:Li IfcLinearForceMeasure:r IfcLinearMomentMeasure:r IfcLinearStiffnessMeasure:r IfcLinearVelocityMeasure:r IfcLogical:b IfcLuminousFluxMeasure:r IfcLuminousIntensityDistributionMeasure:r IfcLuminousIntensityMeasure:r IfcMagneticFluxDensityMeasure:r IfcMagneticFluxMeasure:r IfcMassDensityMeasure:r IfcMassFlowRateMeasure:r IfcMassMeasure:r IfcMassPerLengthMeasure:r IfcModulusOfElasticityMeasure:r IfcModulusOfLinearSubgradeReactionMeasure:r IfcModulusOfRotationalSubgradeReactionMeasure:r IfcModulusOfSubgradeReactionMeasure:r IfcMoistureDiffusivityMeasure:r IfcMolecularWeightMeasure:r IfcMomentOfInertiaMeasure:r IfcMonetaryMeasure:r IfcMonthInYearNumber:i IfcNonNegativeLengthMeasure:r IfcNormalisedRatioMeasure:r IfcNumericMeasure:u IfcPHMeasure:r IfcParameterValue:r IfcPlanarForceMeasure:r IfcPlaneAngleMeasure:r IfcPositiveInteger:i IfcPositiveLengthMeasure:r IfcPositivePlaneAngleMeasure:r IfcPositiveRatioMeasure:r IfcPowerMeasure:r IfcPresentableText:s IfcPressureMeasure:r IfcPropertySetDefinitionSet:E IfcRadioActivityMeasure:r IfcRatioMeasure:r IfcReal:r IfcRotationalFrequencyMeasure:r IfcRotationalMassMeasure:r IfcRotationalStiffnessMeasure:r IfcSectionModulusMeasure:r IfcSectionalAreaIntegralMeasure:r IfcShearModulusMeasure:r IfcSolidAngleMeasure:r IfcSoundPowerLevelMeasure:r IfcSoundPowerMeasure:r IfcSoundPressureLevelMeasure:r IfcSoundPressureMeasure:r IfcSpecificHeatCapacityMeasure:r IfcSpecularExponent:r IfcSpecularRoughness:r IfcTemperatureGradientMeasure:r IfcTemperatureRateOfChangeMeasure:r IfcText:s IfcTextAlignment:s IfcTextDecoration:s IfcTextFontName:s IfcTextTransformation:s IfcThermalAdmittanceMeasure:r IfcThermalConductivityMeasure:r IfcThermalExpansionCoefficientMeasure:r IfcThermalResistanceMeasure:r IfcThermalTransmittanceMeasure:r IfcThermodynamicTemperatureMeasure:r IfcTime:s IfcTimeMeasure:r IfcTimeStamp:i IfcTorqueMeasure:r IfcURIReference:s IfcVaporPermeabilityMeasure:r IfcVolumeMeasure:r IfcVolumetricFlowRateMeasure:r IfcWarpingConstantMeasure:r IfcWarpingMomentMeasure:r"
}
