// Oanarina Archi Tool — GPL-3.0-or-later
// IFC2X3 entity attribute table (ifcXML, schema validation) (generated from IfcOpenShell's schema definition, LGPL-3.0-or-later,
// (c) IfcOpenShell contributors; only names and attribute kinds are used). Line format:
// Entity|Supertype|Attribute:kind,…|derived mask of all attributes[|abstract]. Kinds:
// s string, r real, u number (integer or real), i integer, b boolean/logical, x binary, n enumeration, e entity (or select of entities), v select that
// may hold a typed value, L<k> list of simple values, M<k> list of lists, E list of entities / select values;
// a trailing ? marks an OPTIONAL attribute.
import Foundation

extension IFCSchemaTable {
    static let ifc2x3Table = """
Ifc2DCompositeCurve|IfcCompositeCurve||00
IfcActionRequest|IfcControl|RequestID:s|000000
IfcActor|IfcObject|TheActor:e|000000
IfcActorRole||Role:n,UserDefinedRole:s?,Description:s?|000
IfcActuatorType|IfcDistributionControlElementType|PredefinedType:n|0000000000
IfcAddress||Purpose:n?,Description:s?,UserDefinedPurpose:s?|000|abstract
IfcAirTerminalBoxType|IfcFlowControllerType|PredefinedType:n|0000000000
IfcAirTerminalType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcAirToAirHeatRecoveryType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcAlarmType|IfcDistributionControlElementType|PredefinedType:n|0000000000
IfcAngularDimension|IfcDimensionCurveDirectedCallout||0
IfcAnnotation|IfcProduct||0000000
IfcAnnotationCurveOccurrence|IfcAnnotationOccurrence||000
IfcAnnotationFillArea|IfcGeometricRepresentationItem|OuterBoundary:e,InnerBoundaries:E?|00
IfcAnnotationFillAreaOccurrence|IfcAnnotationOccurrence|FillStyleTarget:e?,GlobalOrLocal:n?|00000
IfcAnnotationOccurrence|IfcStyledItem||000|abstract
IfcAnnotationSurface|IfcGeometricRepresentationItem|Item:e,TextureCoordinates:e?|00
IfcAnnotationSurfaceOccurrence|IfcAnnotationOccurrence||000
IfcAnnotationSymbolOccurrence|IfcAnnotationOccurrence||000
IfcAnnotationTextOccurrence|IfcAnnotationOccurrence||000
IfcApplication||ApplicationDeveloper:e,Version:s,ApplicationFullName:s,ApplicationIdentifier:s|0000
IfcAppliedValue||Name:s?,Description:s?,AppliedValue:v?,UnitBasis:e?,ApplicableDate:e?,FixedUntilDate:e?|000000|abstract
IfcAppliedValueRelationship||ComponentOfTotal:e,Components:E,ArithmeticOperator:n,Name:s?,Description:s?|00000
IfcApproval||Description:s?,ApprovalDateTime:e,ApprovalStatus:s?,ApprovalLevel:s?,ApprovalQualifier:s?,Name:s,Identifier:s|0000000
IfcApprovalActorRelationship||Actor:e,Approval:e,Role:e|000
IfcApprovalPropertyRelationship||ApprovedProperties:E,Approval:e|00
IfcApprovalRelationship||RelatedApproval:e,RelatingApproval:e,Description:s?,Name:s|0000
IfcArbitraryClosedProfileDef|IfcProfileDef|OuterCurve:e|000
IfcArbitraryOpenProfileDef|IfcProfileDef|Curve:e|000
IfcArbitraryProfileDefWithVoids|IfcArbitraryClosedProfileDef|InnerCurves:E|0000
IfcAsset|IfcGroup|AssetID:s,OriginalValue:e,CurrentValue:e,TotalReplacementCost:e,Owner:e,User:e,ResponsiblePerson:e,IncorporationDate:e,DepreciatedValue:e|00000000000000
IfcAsymmetricIShapeProfileDef|IfcIShapeProfileDef|TopFlangeWidth:r,TopFlangeThickness:r?,TopFlangeFilletRadius:r?,CentreOfGravityInY:r?|000000000000
IfcAxis1Placement|IfcPlacement|Axis:e?|00
IfcAxis2Placement2D|IfcPlacement|RefDirection:e?|00
IfcAxis2Placement3D|IfcPlacement|Axis:e?,RefDirection:e?|000
IfcBSplineCurve|IfcBoundedCurve|Degree:i,ControlPointsList:E,CurveForm:n,ClosedCurve:b,SelfIntersect:b|00000|abstract
IfcBeam|IfcBuildingElement||00000000
IfcBeamType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcBezierCurve|IfcBSplineCurve||00000
IfcBlobTexture|IfcSurfaceTexture|RasterFormat:s,RasterCode:b|000000
IfcBlock|IfcCsgPrimitive3D|XLength:r,YLength:r,ZLength:r|0000
IfcBoilerType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcBooleanClippingResult|IfcBooleanResult||000
IfcBooleanResult|IfcGeometricRepresentationItem|Operator:n,FirstOperand:e,SecondOperand:e|000
IfcBoundaryCondition||Name:s?|0|abstract
IfcBoundaryEdgeCondition|IfcBoundaryCondition|LinearStiffnessByLengthX:r?,LinearStiffnessByLengthY:r?,LinearStiffnessByLengthZ:r?,RotationalStiffnessByLengthX:r?,RotationalStiffnessByLengthY:r?,RotationalStiffnessByLengthZ:r?|0000000
IfcBoundaryFaceCondition|IfcBoundaryCondition|LinearStiffnessByAreaX:r?,LinearStiffnessByAreaY:r?,LinearStiffnessByAreaZ:r?|0000
IfcBoundaryNodeCondition|IfcBoundaryCondition|LinearStiffnessX:r?,LinearStiffnessY:r?,LinearStiffnessZ:r?,RotationalStiffnessX:r?,RotationalStiffnessY:r?,RotationalStiffnessZ:r?|0000000
IfcBoundaryNodeConditionWarping|IfcBoundaryNodeCondition|WarpingStiffness:r?|00000000
IfcBoundedCurve|IfcCurve|||abstract
IfcBoundedSurface|IfcSurface||
IfcBoundingBox|IfcGeometricRepresentationItem|Corner:e,XDim:r,YDim:r,ZDim:r|0000
IfcBoxedHalfSpace|IfcHalfSpaceSolid|Enclosure:e|000
IfcBuilding|IfcSpatialStructureElement|ElevationOfRefHeight:r?,ElevationOfTerrain:r?,BuildingAddress:e?|000000000000
IfcBuildingElement|IfcElement||00000000|abstract
IfcBuildingElementComponent|IfcBuildingElement||00000000|abstract
IfcBuildingElementPart|IfcBuildingElementComponent||00000000
IfcBuildingElementProxy|IfcBuildingElement|CompositionType:n?|000000000
IfcBuildingElementProxyType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcBuildingElementType|IfcElementType||000000000|abstract
IfcBuildingStorey|IfcSpatialStructureElement|Elevation:r?|0000000000
IfcCShapeProfileDef|IfcParameterizedProfileDef|Depth:r,Width:r,WallThickness:r,Girth:r,InternalFilletRadius:r?,CentreOfGravityInX:r?|000000000
IfcCableCarrierFittingType|IfcFlowFittingType|PredefinedType:n|0000000000
IfcCableCarrierSegmentType|IfcFlowSegmentType|PredefinedType:n|0000000000
IfcCableSegmentType|IfcFlowSegmentType|PredefinedType:n|0000000000
IfcCalendarDate||DayComponent:i,MonthComponent:i,YearComponent:i|000
IfcCartesianPoint|IfcPoint|Coordinates:Lr|0
IfcCartesianTransformationOperator|IfcGeometricRepresentationItem|Axis1:e?,Axis2:e?,LocalOrigin:e,Scale:r?|0000|abstract
IfcCartesianTransformationOperator2D|IfcCartesianTransformationOperator||0000
IfcCartesianTransformationOperator2DnonUniform|IfcCartesianTransformationOperator2D|Scale2:r?|00000
IfcCartesianTransformationOperator3D|IfcCartesianTransformationOperator|Axis3:e?|00000
IfcCartesianTransformationOperator3DnonUniform|IfcCartesianTransformationOperator3D|Scale2:r?,Scale3:r?|0000000
IfcCenterLineProfileDef|IfcArbitraryOpenProfileDef|Thickness:r|0000
IfcChamferEdgeFeature|IfcEdgeFeature|Width:r?,Height:r?|00000000000
IfcChillerType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcCircle|IfcConic|Radius:r|00
IfcCircleHollowProfileDef|IfcCircleProfileDef|WallThickness:r|00000
IfcCircleProfileDef|IfcParameterizedProfileDef|Radius:r|0000
IfcClassification||Source:s,Edition:s,EditionDate:e?,Name:s|0000
IfcClassificationItem||Notation:e,ItemOf:e?,Title:s|000
IfcClassificationItemRelationship||RelatingItem:e,RelatedItems:E|00
IfcClassificationNotation||NotationFacets:E|0
IfcClassificationNotationFacet||NotationValue:s|0
IfcClassificationReference|IfcExternalReference|ReferencedSource:e?|0000
IfcClosedShell|IfcConnectedFaceSet||0
IfcCoilType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcColourRgb|IfcColourSpecification|Red:r,Green:r,Blue:r|0000
IfcColourSpecification||Name:s?|0|abstract
IfcColumn|IfcBuildingElement||00000000
IfcColumnType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcComplexProperty|IfcProperty|UsageName:s,HasProperties:E|0000
IfcCompositeCurve|IfcBoundedCurve|Segments:E,SelfIntersect:b|00
IfcCompositeCurveSegment|IfcGeometricRepresentationItem|Transition:n,SameSense:b,ParentCurve:e|000
IfcCompositeProfileDef|IfcProfileDef|Profiles:E,Label:s?|0000
IfcCompressorType|IfcFlowMovingDeviceType|PredefinedType:n|0000000000
IfcCondenserType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcCondition|IfcGroup||00000
IfcConditionCriterion|IfcControl|Criterion:v,CriterionDateTime:e|0000000
IfcConic|IfcCurve|Position:e|0|abstract
IfcConnectedFaceSet|IfcTopologicalRepresentationItem|CfsFaces:E|0
IfcConnectionCurveGeometry|IfcConnectionGeometry|CurveOnRelatingElement:e,CurveOnRelatedElement:e?|00
IfcConnectionGeometry||||abstract
IfcConnectionPointEccentricity|IfcConnectionPointGeometry|EccentricityInX:r?,EccentricityInY:r?,EccentricityInZ:r?|00000
IfcConnectionPointGeometry|IfcConnectionGeometry|PointOnRelatingElement:e,PointOnRelatedElement:e?|00
IfcConnectionPortGeometry|IfcConnectionGeometry|LocationAtRelatingElement:e,LocationAtRelatedElement:e?,ProfileOfPort:e|000
IfcConnectionSurfaceGeometry|IfcConnectionGeometry|SurfaceOnRelatingElement:e,SurfaceOnRelatedElement:e?|00
IfcConstraint||Name:s,Description:s?,ConstraintGrade:n,ConstraintSource:s?,CreatingActor:e?,CreationTime:e?,UserDefinedGrade:s?|0000000|abstract
IfcConstraintAggregationRelationship||Name:s?,Description:s?,RelatingConstraint:e,RelatedConstraints:E,LogicalAggregator:n|00000
IfcConstraintClassificationRelationship||ClassifiedConstraint:e,RelatedClassifications:E|00
IfcConstraintRelationship||Name:s?,Description:s?,RelatingConstraint:e,RelatedConstraints:E|0000
IfcConstructionEquipmentResource|IfcConstructionResource||000000000
IfcConstructionMaterialResource|IfcConstructionResource|Suppliers:E?,UsageRatio:r?|00000000000
IfcConstructionProductResource|IfcConstructionResource||000000000
IfcConstructionResource|IfcResource|ResourceIdentifier:s?,ResourceGroup:s?,ResourceConsumption:n?,BaseQuantity:e?|000000000|abstract
IfcContextDependentUnit|IfcNamedUnit|Name:s|000
IfcControl|IfcObject||00000|abstract
IfcControllerType|IfcDistributionControlElementType|PredefinedType:n|0000000000
IfcConversionBasedUnit|IfcNamedUnit|Name:s,ConversionFactor:e|0000
IfcCooledBeamType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcCoolingTowerType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcCoordinatedUniversalTimeOffset||HourOffset:i,MinuteOffset:i?,Sense:n|000
IfcCostItem|IfcControl||00000
IfcCostSchedule|IfcControl|SubmittedBy:e?,PreparedBy:e?,SubmittedOn:e?,Status:s?,TargetUsers:E?,UpdateDate:e?,ID:s,PredefinedType:n|0000000000000
IfcCostValue|IfcAppliedValue|CostType:s,Condition:s?|00000000
IfcCovering|IfcBuildingElement|PredefinedType:n?|000000000
IfcCoveringType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcCraneRailAShapeProfileDef|IfcParameterizedProfileDef|OverallHeight:r,BaseWidth2:r,Radius:r?,HeadWidth:r,HeadDepth2:r,HeadDepth3:r,WebThickness:r,BaseWidth4:r,BaseDepth1:r,BaseDepth2:r,BaseDepth3:r,CentreOfGravityInY:r?|000000000000000
IfcCraneRailFShapeProfileDef|IfcParameterizedProfileDef|OverallHeight:r,HeadWidth:r,Radius:r?,HeadDepth2:r,HeadDepth3:r,WebThickness:r,BaseDepth1:r,BaseDepth2:r,CentreOfGravityInY:r?|000000000000
IfcCrewResource|IfcConstructionResource||000000000
IfcCsgPrimitive3D|IfcGeometricRepresentationItem|Position:e|0|abstract
IfcCsgSolid|IfcSolidModel|TreeRootExpression:e|0
IfcCurrencyRelationship||RelatingMonetaryUnit:e,RelatedMonetaryUnit:e,ExchangeRate:r,RateDateTime:e,RateSource:e?|00000
IfcCurtainWall|IfcBuildingElement||00000000
IfcCurtainWallType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcCurve|IfcGeometricRepresentationItem|||abstract
IfcCurveBoundedPlane|IfcBoundedSurface|BasisSurface:e,OuterBoundary:e,InnerBoundaries:E|000
IfcCurveStyle|IfcPresentationStyle|CurveFont:e?,CurveWidth:v?,CurveColour:e?|0000
IfcCurveStyleFont||Name:s?,PatternList:E|00
IfcCurveStyleFontAndScaling||Name:s?,CurveFont:e,CurveFontScaling:r|000
IfcCurveStyleFontPattern||VisibleSegmentLength:r,InvisibleSegmentLength:r|00
IfcDamperType|IfcFlowControllerType|PredefinedType:n|0000000000
IfcDateAndTime||DateComponent:e,TimeComponent:e|00
IfcDefinedSymbol|IfcGeometricRepresentationItem|Definition:e,Target:e|00
IfcDerivedProfileDef|IfcProfileDef|ParentProfile:e,Operator:e,Label:s?|00000
IfcDerivedUnit||Elements:E,UnitType:n,UserDefinedType:s?|000
IfcDerivedUnitElement||Unit:e,Exponent:i|00
IfcDiameterDimension|IfcDimensionCurveDirectedCallout||0
IfcDimensionCalloutRelationship|IfcDraughtingCalloutRelationship||0000
IfcDimensionCurve|IfcAnnotationCurveOccurrence||000
IfcDimensionCurveDirectedCallout|IfcDraughtingCallout||0
IfcDimensionCurveTerminator|IfcTerminatorSymbol|Role:n|00000
IfcDimensionPair|IfcDraughtingCalloutRelationship||0000
IfcDimensionalExponents||LengthExponent:i,MassExponent:i,TimeExponent:i,ElectricCurrentExponent:i,ThermodynamicTemperatureExponent:i,AmountOfSubstanceExponent:i,LuminousIntensityExponent:i|0000000
IfcDirection|IfcGeometricRepresentationItem|DirectionRatios:Lr|0
IfcDiscreteAccessory|IfcElementComponent||00000000
IfcDiscreteAccessoryType|IfcElementComponentType||000000000
IfcDistributionChamberElement|IfcDistributionFlowElement||00000000
IfcDistributionChamberElementType|IfcDistributionFlowElementType|PredefinedType:n|0000000000
IfcDistributionControlElement|IfcDistributionElement|ControlElementId:s?|000000000
IfcDistributionControlElementType|IfcDistributionElementType||000000000|abstract
IfcDistributionElement|IfcElement||00000000
IfcDistributionElementType|IfcElementType||000000000
IfcDistributionFlowElement|IfcDistributionElement||00000000
IfcDistributionFlowElementType|IfcDistributionElementType||000000000|abstract
IfcDistributionPort|IfcPort|FlowDirection:n?|00000000
IfcDocumentElectronicFormat||FileExtension:s?,MimeContentType:s?,MimeSubtype:s?|000
IfcDocumentInformation||DocumentId:s,Name:s,Description:s?,DocumentReferences:E?,Purpose:s?,IntendedUse:s?,Scope:s?,Revision:s?,DocumentOwner:e?,Editors:E?,CreationTime:e?,LastRevisionTime:e?,ElectronicFormat:e?,ValidFrom:e?,ValidUntil:e?,Confidentiality:n?,Status:n?|00000000000000000
IfcDocumentInformationRelationship||RelatingDocument:e,RelatedDocuments:E,RelationshipType:s?|000
IfcDocumentReference|IfcExternalReference||000
IfcDoor|IfcBuildingElement|OverallHeight:r?,OverallWidth:r?|0000000000
IfcDoorLiningProperties|IfcPropertySetDefinition|LiningDepth:r?,LiningThickness:r?,ThresholdDepth:r?,ThresholdThickness:r?,TransomThickness:r?,TransomOffset:r?,LiningOffset:r?,ThresholdOffset:r?,CasingThickness:r?,CasingDepth:r?,ShapeAspectStyle:e?|000000000000000
IfcDoorPanelProperties|IfcPropertySetDefinition|PanelDepth:r?,PanelOperation:n,PanelWidth:r?,PanelPosition:n,ShapeAspectStyle:e?|000000000
IfcDoorStyle|IfcTypeProduct|OperationType:n,ConstructionType:n,ParameterTakesPrecedence:b,Sizeable:b|000000000000
IfcDraughtingCallout|IfcGeometricRepresentationItem|Contents:E|0
IfcDraughtingCalloutRelationship||Name:s?,Description:s?,RelatingDraughtingCallout:e,RelatedDraughtingCallout:e|0000
IfcDraughtingPreDefinedColour|IfcPreDefinedColour||0
IfcDraughtingPreDefinedCurveFont|IfcPreDefinedCurveFont||0
IfcDraughtingPreDefinedTextFont|IfcPreDefinedTextFont||0
IfcDuctFittingType|IfcFlowFittingType|PredefinedType:n|0000000000
IfcDuctSegmentType|IfcFlowSegmentType|PredefinedType:n|0000000000
IfcDuctSilencerType|IfcFlowTreatmentDeviceType|PredefinedType:n|0000000000
IfcEdge|IfcTopologicalRepresentationItem|EdgeStart:e,EdgeEnd:e|00
IfcEdgeCurve|IfcEdge|EdgeGeometry:e,SameSense:b|0000
IfcEdgeFeature|IfcFeatureElementSubtraction|FeatureLength:r?|000000000|abstract
IfcEdgeLoop|IfcLoop|EdgeList:E|0
IfcElectricApplianceType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcElectricDistributionPoint|IfcFlowController|DistributionPointFunction:n,UserDefinedFunction:s?|0000000000
IfcElectricFlowStorageDeviceType|IfcFlowStorageDeviceType|PredefinedType:n|0000000000
IfcElectricGeneratorType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcElectricHeaterType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcElectricMotorType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcElectricTimeControlType|IfcFlowControllerType|PredefinedType:n|0000000000
IfcElectricalBaseProperties|IfcEnergyProperties|ElectricCurrentType:n?,InputVoltage:r,InputFrequency:r,FullLoadCurrent:r?,MinimumCircuitCurrent:r?,MaximumPowerInput:r?,RatedPowerInput:r?,InputPhase:i|00000000000000
IfcElectricalCircuit|IfcSystem||00000
IfcElectricalElement|IfcElement||00000000
IfcElement|IfcProduct|Tag:s?|00000000|abstract
IfcElementAssembly|IfcElement|AssemblyPlace:n?,PredefinedType:n|0000000000
IfcElementComponent|IfcElement||00000000|abstract
IfcElementComponentType|IfcElementType||000000000|abstract
IfcElementQuantity|IfcPropertySetDefinition|MethodOfMeasurement:s?,Quantities:E|000000
IfcElementType|IfcTypeProduct|ElementType:s?|000000000|abstract
IfcElementarySurface|IfcSurface|Position:e|0|abstract
IfcEllipse|IfcConic|SemiAxis1:r,SemiAxis2:r|000
IfcEllipseProfileDef|IfcParameterizedProfileDef|SemiAxis1:r,SemiAxis2:r|00000
IfcEnergyConversionDevice|IfcDistributionFlowElement||00000000
IfcEnergyConversionDeviceType|IfcDistributionFlowElementType||000000000|abstract
IfcEnergyProperties|IfcPropertySetDefinition|EnergySequence:n?,UserDefinedEnergySequence:s?|000000
IfcEnvironmentalImpactValue|IfcAppliedValue|ImpactType:s,Category:n,UserDefinedCategory:s?|000000000
IfcEquipmentElement|IfcElement||00000000
IfcEquipmentStandard|IfcControl||00000
IfcEvaporativeCoolerType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcEvaporatorType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcExtendedMaterialProperties|IfcMaterialProperties|ExtendedProperties:E,Description:s?,Name:s|0000
IfcExternalReference||Location:s?,ItemReference:s?,Name:s?|000|abstract
IfcExternallyDefinedHatchStyle|IfcExternalReference||000
IfcExternallyDefinedSurfaceStyle|IfcExternalReference||000
IfcExternallyDefinedSymbol|IfcExternalReference||000
IfcExternallyDefinedTextFont|IfcExternalReference||000
IfcExtrudedAreaSolid|IfcSweptAreaSolid|ExtrudedDirection:e,Depth:r|0000
IfcFace|IfcTopologicalRepresentationItem|Bounds:E|0
IfcFaceBasedSurfaceModel|IfcGeometricRepresentationItem|FbsmFaces:E|0
IfcFaceBound|IfcTopologicalRepresentationItem|Bound:e,Orientation:b|00
IfcFaceOuterBound|IfcFaceBound||00
IfcFaceSurface|IfcFace|FaceSurface:e,SameSense:b|000
IfcFacetedBrep|IfcManifoldSolidBrep||0
IfcFacetedBrepWithVoids|IfcManifoldSolidBrep|Voids:E|00
IfcFailureConnectionCondition|IfcStructuralConnectionCondition|TensionFailureX:r?,TensionFailureY:r?,TensionFailureZ:r?,CompressionFailureX:r?,CompressionFailureY:r?,CompressionFailureZ:r?|0000000
IfcFanType|IfcFlowMovingDeviceType|PredefinedType:n|0000000000
IfcFastener|IfcElementComponent||00000000
IfcFastenerType|IfcElementComponentType||000000000
IfcFeatureElement|IfcElement||00000000|abstract
IfcFeatureElementAddition|IfcFeatureElement||00000000|abstract
IfcFeatureElementSubtraction|IfcFeatureElement||00000000|abstract
IfcFillAreaStyle|IfcPresentationStyle|FillStyles:E|00
IfcFillAreaStyleHatching|IfcGeometricRepresentationItem|HatchLineAppearance:e,StartOfNextHatchLine:v,PointOfReferenceHatchLine:e?,PatternStart:e?,HatchLineAngle:r|00000
IfcFillAreaStyleTileSymbolWithStyle|IfcGeometricRepresentationItem|Symbol:e|0
IfcFillAreaStyleTiles|IfcGeometricRepresentationItem|TilingPattern:e,Tiles:E,TilingScale:r|000
IfcFilterType|IfcFlowTreatmentDeviceType|PredefinedType:n|0000000000
IfcFireSuppressionTerminalType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcFlowController|IfcDistributionFlowElement||00000000
IfcFlowControllerType|IfcDistributionFlowElementType||000000000|abstract
IfcFlowFitting|IfcDistributionFlowElement||00000000
IfcFlowFittingType|IfcDistributionFlowElementType||000000000|abstract
IfcFlowInstrumentType|IfcDistributionControlElementType|PredefinedType:n|0000000000
IfcFlowMeterType|IfcFlowControllerType|PredefinedType:n|0000000000
IfcFlowMovingDevice|IfcDistributionFlowElement||00000000
IfcFlowMovingDeviceType|IfcDistributionFlowElementType||000000000|abstract
IfcFlowSegment|IfcDistributionFlowElement||00000000
IfcFlowSegmentType|IfcDistributionFlowElementType||000000000|abstract
IfcFlowStorageDevice|IfcDistributionFlowElement||00000000
IfcFlowStorageDeviceType|IfcDistributionFlowElementType||000000000|abstract
IfcFlowTerminal|IfcDistributionFlowElement||00000000
IfcFlowTerminalType|IfcDistributionFlowElementType||000000000|abstract
IfcFlowTreatmentDevice|IfcDistributionFlowElement||00000000
IfcFlowTreatmentDeviceType|IfcDistributionFlowElementType||000000000|abstract
IfcFluidFlowProperties|IfcPropertySetDefinition|PropertySource:n,FlowConditionTimeSeries:e?,VelocityTimeSeries:e?,FlowrateTimeSeries:e?,Fluid:e,PressureTimeSeries:e?,UserDefinedPropertySource:s?,TemperatureSingleValue:r?,WetBulbTemperatureSingleValue:r?,WetBulbTemperatureTimeSeries:e?,TemperatureTimeSeries:e?,FlowrateSingleValue:v?,FlowConditionSingleValue:r?,VelocitySingleValue:r?,PressureSingleValue:r?|0000000000000000000
IfcFooting|IfcBuildingElement|PredefinedType:n|000000000
IfcFuelProperties|IfcMaterialProperties|CombustionTemperature:r?,CarbonContent:r?,LowerHeatingValue:r?,HigherHeatingValue:r?|00000
IfcFurnishingElement|IfcElement||00000000
IfcFurnishingElementType|IfcElementType||000000000
IfcFurnitureStandard|IfcControl||00000
IfcFurnitureType|IfcFurnishingElementType|AssemblyPlace:n|0000000000
IfcGasTerminalType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcGeneralMaterialProperties|IfcMaterialProperties|MolecularWeight:r?,Porosity:r?,MassDensity:r?|0000
IfcGeneralProfileProperties|IfcProfileProperties|PhysicalWeight:r?,Perimeter:r?,MinimumPlateThickness:r?,MaximumPlateThickness:r?,CrossSectionArea:r?|0000000
IfcGeometricCurveSet|IfcGeometricSet||0
IfcGeometricRepresentationContext|IfcRepresentationContext|CoordinateSpaceDimension:i,Precision:r?,WorldCoordinateSystem:e,TrueNorth:e?|000000
IfcGeometricRepresentationItem|IfcRepresentationItem|||abstract
IfcGeometricRepresentationSubContext|IfcGeometricRepresentationContext|ParentContext:e,TargetScale:r?,TargetView:n,UserDefinedTargetView:s?|0011110000
IfcGeometricSet|IfcGeometricRepresentationItem|Elements:E|0
IfcGrid|IfcProduct|UAxes:E,VAxes:E,WAxes:E?|0000000000
IfcGridAxis||AxisTag:s?,AxisCurve:e,SameSense:b|000
IfcGridPlacement|IfcObjectPlacement|PlacementLocation:e,PlacementRefDirection:e?|00
IfcGroup|IfcObject||00000
IfcHalfSpaceSolid|IfcGeometricRepresentationItem|BaseSurface:e,AgreementFlag:b|00
IfcHeatExchangerType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcHumidifierType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcHygroscopicMaterialProperties|IfcMaterialProperties|UpperVaporResistanceFactor:r?,LowerVaporResistanceFactor:r?,IsothermalMoistureCapacity:r?,VaporPermeability:r?,MoistureDiffusivity:r?|000000
IfcIShapeProfileDef|IfcParameterizedProfileDef|OverallWidth:r,OverallDepth:r,WebThickness:r,FlangeThickness:r,FilletRadius:r?|00000000
IfcImageTexture|IfcSurfaceTexture|UrlReference:s|00000
IfcInventory|IfcGroup|InventoryType:n,Jurisdiction:e,ResponsiblePersons:E,LastUpdateDate:e,CurrentValue:e?,OriginalValue:e?|00000000000
IfcIrregularTimeSeries|IfcTimeSeries|Values:E|000000000
IfcIrregularTimeSeriesValue||TimeStamp:e,ListValues:E|00
IfcJunctionBoxType|IfcFlowFittingType|PredefinedType:n|0000000000
IfcLShapeProfileDef|IfcParameterizedProfileDef|Depth:r,Width:r?,Thickness:r,FilletRadius:r?,EdgeRadius:r?,LegSlope:r?,CentreOfGravityInX:r?,CentreOfGravityInY:r?|00000000000
IfcLaborResource|IfcConstructionResource|SkillSet:s?|0000000000
IfcLampType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcLibraryInformation||Name:s,Version:s?,Publisher:e?,VersionDate:e?,LibraryReference:E?|00000
IfcLibraryReference|IfcExternalReference||000
IfcLightDistributionData||MainPlaneAngle:r,SecondaryPlaneAngle:Lr,LuminousIntensity:Lr|000
IfcLightFixtureType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcLightIntensityDistribution||LightDistributionCurve:n,DistributionData:E|00
IfcLightSource|IfcGeometricRepresentationItem|Name:s?,LightColour:e,AmbientIntensity:r?,Intensity:r?|0000|abstract
IfcLightSourceAmbient|IfcLightSource||0000
IfcLightSourceDirectional|IfcLightSource|Orientation:e|00000
IfcLightSourceGoniometric|IfcLightSource|Position:e,ColourAppearance:e?,ColourTemperature:r,LuminousFlux:r,LightEmissionSource:n,LightDistributionDataSource:e|0000000000
IfcLightSourcePositional|IfcLightSource|Position:e,Radius:r,ConstantAttenuation:r,DistanceAttenuation:r,QuadricAttenuation:r|000000000
IfcLightSourceSpot|IfcLightSourcePositional|Orientation:e,ConcentrationExponent:r?,SpreadAngle:r,BeamWidthAngle:r|0000000000000
IfcLine|IfcCurve|Pnt:e,Dir:e|00
IfcLinearDimension|IfcDimensionCurveDirectedCallout||0
IfcLocalPlacement|IfcObjectPlacement|PlacementRelTo:e?,RelativePlacement:e|00
IfcLocalTime||HourComponent:i,MinuteComponent:i?,SecondComponent:r?,Zone:e?,DaylightSavingOffset:i?|00000
IfcLoop|IfcTopologicalRepresentationItem||
IfcManifoldSolidBrep|IfcSolidModel|Outer:e|0|abstract
IfcMappedItem|IfcRepresentationItem|MappingSource:e,MappingTarget:e|00
IfcMaterial||Name:s|0
IfcMaterialClassificationRelationship||MaterialClassifications:E,ClassifiedMaterial:e|00
IfcMaterialDefinitionRepresentation|IfcProductRepresentation|RepresentedMaterial:e|0000
IfcMaterialLayer||Material:e?,LayerThickness:r,IsVentilated:b?|000
IfcMaterialLayerSet||MaterialLayers:E,LayerSetName:s?|00
IfcMaterialLayerSetUsage||ForLayerSet:e,LayerSetDirection:n,DirectionSense:n,OffsetFromReferenceLine:r|0000
IfcMaterialList||Materials:E|0
IfcMaterialProperties||Material:e|0|abstract
IfcMeasureWithUnit||ValueComponent:v,UnitComponent:e|00
IfcMechanicalConcreteMaterialProperties|IfcMechanicalMaterialProperties|CompressiveStrength:r?,MaxAggregateSize:r?,AdmixturesDescription:s?,Workability:s?,ProtectivePoreRatio:r?,WaterImpermeability:s?|000000000000
IfcMechanicalFastener|IfcFastener|NominalDiameter:r?,NominalLength:r?|0000000000
IfcMechanicalFastenerType|IfcFastenerType||000000000
IfcMechanicalMaterialProperties|IfcMaterialProperties|DynamicViscosity:r?,YoungModulus:r?,ShearModulus:r?,PoissonRatio:r?,ThermalExpansionCoefficient:r?|000000
IfcMechanicalSteelMaterialProperties|IfcMechanicalMaterialProperties|YieldStress:r?,UltimateStress:r?,UltimateStrain:r?,HardeningModule:r?,ProportionalStress:r?,PlasticStrain:r?,Relaxations:E?|0000000000000
IfcMember|IfcBuildingElement||00000000
IfcMemberType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcMetric|IfcConstraint|Benchmark:n,ValueSource:s?,DataValue:v|0000000000
IfcMonetaryUnit||Currency:n|0
IfcMotorConnectionType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcMove|IfcTask|MoveFrom:e,MoveTo:e,PunchList:Ls?|0000000000000
IfcNamedUnit||Dimensions:e,UnitType:n|00|abstract
IfcObject|IfcObjectDefinition|ObjectType:s?|00000|abstract
IfcObjectDefinition|IfcRoot||0000|abstract
IfcObjectPlacement||||abstract
IfcObjective|IfcConstraint|BenchmarkValues:e?,ResultValues:e?,ObjectiveQualifier:n,UserDefinedQualifier:s?|00000000000
IfcOccupant|IfcActor|PredefinedType:n|0000000
IfcOffsetCurve2D|IfcCurve|BasisCurve:e,Distance:r,SelfIntersect:b|000
IfcOffsetCurve3D|IfcCurve|BasisCurve:e,Distance:r,SelfIntersect:b,RefDirection:e|0000
IfcOneDirectionRepeatFactor|IfcGeometricRepresentationItem|RepeatFactor:e|0
IfcOpenShell|IfcConnectedFaceSet||0
IfcOpeningElement|IfcFeatureElementSubtraction||00000000
IfcOpticalMaterialProperties|IfcMaterialProperties|VisibleTransmittance:r?,SolarTransmittance:r?,ThermalIrTransmittance:r?,ThermalIrEmissivityBack:r?,ThermalIrEmissivityFront:r?,VisibleReflectanceBack:r?,VisibleReflectanceFront:r?,SolarReflectanceFront:r?,SolarReflectanceBack:r?|0000000000
IfcOrderAction|IfcTask|ActionID:s|00000000000
IfcOrganization||Id:s?,Name:s,Description:s?,Roles:E?,Addresses:E?|00000
IfcOrganizationRelationship||Name:s,Description:s?,RelatingOrganization:e,RelatedOrganizations:E|0000
IfcOrientedEdge|IfcEdge|EdgeElement:e,Orientation:b|1100
IfcOutletType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcOwnerHistory||OwningUser:e,OwningApplication:e,State:n?,ChangeAction:n,LastModifiedDate:i?,LastModifyingUser:e?,LastModifyingApplication:e?,CreationDate:i|00000000
IfcParameterizedProfileDef|IfcProfileDef|Position:e|000|abstract
IfcPath|IfcTopologicalRepresentationItem|EdgeList:E|0
IfcPerformanceHistory|IfcControl|LifeCyclePhase:s|000000
IfcPermeableCoveringProperties|IfcPropertySetDefinition|OperationType:n,PanelPosition:n,FrameDepth:r?,FrameThickness:r?,ShapeAspectStyle:e?|000000000
IfcPermit|IfcControl|PermitID:s|000000
IfcPerson||Id:s?,FamilyName:s?,GivenName:s?,MiddleNames:Ls?,PrefixTitles:Ls?,SuffixTitles:Ls?,Roles:E?,Addresses:E?|00000000
IfcPersonAndOrganization||ThePerson:e,TheOrganization:e,Roles:E?|000
IfcPhysicalComplexQuantity|IfcPhysicalQuantity|HasQuantities:E,Discrimination:s,Quality:s?,Usage:s?|000000
IfcPhysicalQuantity||Name:s,Description:s?|00|abstract
IfcPhysicalSimpleQuantity|IfcPhysicalQuantity|Unit:e?|000|abstract
IfcPile|IfcBuildingElement|PredefinedType:n,ConstructionType:n?|0000000000
IfcPipeFittingType|IfcFlowFittingType|PredefinedType:n|0000000000
IfcPipeSegmentType|IfcFlowSegmentType|PredefinedType:n|0000000000
IfcPixelTexture|IfcSurfaceTexture|Width:i,Height:i,ColourComponents:i,Pixel:Lx|00000000
IfcPlacement|IfcGeometricRepresentationItem|Location:e|0|abstract
IfcPlanarBox|IfcPlanarExtent|Placement:e|000
IfcPlanarExtent|IfcGeometricRepresentationItem|SizeInX:r,SizeInY:r|00
IfcPlane|IfcElementarySurface||0
IfcPlate|IfcBuildingElement||00000000
IfcPlateType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcPoint|IfcGeometricRepresentationItem|||abstract
IfcPointOnCurve|IfcPoint|BasisCurve:e,PointParameter:r|00
IfcPointOnSurface|IfcPoint|BasisSurface:e,PointParameterU:r,PointParameterV:r|000
IfcPolyLoop|IfcLoop|Polygon:E|0
IfcPolygonalBoundedHalfSpace|IfcHalfSpaceSolid|Position:e,PolygonalBoundary:e|0000
IfcPolyline|IfcBoundedCurve|Points:E|0
IfcPort|IfcProduct||0000000|abstract
IfcPostalAddress|IfcAddress|InternalLocation:s?,AddressLines:Ls?,PostalBox:s?,Town:s?,Region:s?,PostalCode:s?,Country:s?|0000000000
IfcPreDefinedColour|IfcPreDefinedItem||0|abstract
IfcPreDefinedCurveFont|IfcPreDefinedItem||0|abstract
IfcPreDefinedDimensionSymbol|IfcPreDefinedSymbol||0
IfcPreDefinedItem||Name:s|0|abstract
IfcPreDefinedPointMarkerSymbol|IfcPreDefinedSymbol||0
IfcPreDefinedSymbol|IfcPreDefinedItem||0|abstract
IfcPreDefinedTerminatorSymbol|IfcPreDefinedSymbol||0
IfcPreDefinedTextFont|IfcPreDefinedItem||0|abstract
IfcPresentationLayerAssignment||Name:s,Description:s?,AssignedItems:E,Identifier:s?|0000
IfcPresentationLayerWithStyle|IfcPresentationLayerAssignment|LayerOn:b,LayerFrozen:b,LayerBlocked:b,LayerStyles:E|00000000
IfcPresentationStyle||Name:s?|0|abstract
IfcPresentationStyleAssignment||Styles:E|0
IfcProcedure|IfcProcess|ProcedureID:s,ProcedureType:n,UserDefinedProcedureType:s?|00000000
IfcProcess|IfcObject||00000|abstract
IfcProduct|IfcObject|ObjectPlacement:e?,Representation:e?|0000000|abstract
IfcProductDefinitionShape|IfcProductRepresentation||000
IfcProductRepresentation||Name:s?,Description:s?,Representations:E|000
IfcProductsOfCombustionProperties|IfcMaterialProperties|SpecificHeatCapacity:r?,N20Content:r?,COContent:r?,CO2Content:r?|00000
IfcProfileDef||ProfileType:n,ProfileName:s?|00|abstract
IfcProfileProperties||ProfileName:s?,ProfileDefinition:e?|00|abstract
IfcProject|IfcObject|LongName:s?,Phase:s?,RepresentationContexts:E,UnitsInContext:e|000000000
IfcProjectOrder|IfcControl|ID:s,PredefinedType:n,Status:s?|00000000
IfcProjectOrderRecord|IfcControl|Records:E,PredefinedType:n|0000000
IfcProjectionCurve|IfcAnnotationCurveOccurrence||000
IfcProjectionElement|IfcFeatureElementAddition||00000000
IfcProperty||Name:s,Description:s?|00|abstract
IfcPropertyBoundedValue|IfcSimpleProperty|UpperBoundValue:v?,LowerBoundValue:v?,Unit:e?|00000
IfcPropertyConstraintRelationship||RelatingConstraint:e,RelatedProperties:E,Name:s?,Description:s?|0000
IfcPropertyDefinition|IfcRoot||0000|abstract
IfcPropertyDependencyRelationship||DependingProperty:e,DependantProperty:e,Name:s?,Description:s?,Expression:s?|00000
IfcPropertyEnumeratedValue|IfcSimpleProperty|EnumerationValues:E,EnumerationReference:e?|0000
IfcPropertyEnumeration||Name:s,EnumerationValues:E,Unit:e?|000
IfcPropertyListValue|IfcSimpleProperty|ListValues:E,Unit:e?|0000
IfcPropertyReferenceValue|IfcSimpleProperty|UsageName:s?,PropertyReference:e|0000
IfcPropertySet|IfcPropertySetDefinition|HasProperties:E|00000
IfcPropertySetDefinition|IfcPropertyDefinition||0000|abstract
IfcPropertySingleValue|IfcSimpleProperty|NominalValue:v?,Unit:e?|0000
IfcPropertyTableValue|IfcSimpleProperty|DefiningValues:E,DefinedValues:E,Expression:s?,DefiningUnit:e?,DefinedUnit:e?|0000000
IfcProtectiveDeviceType|IfcFlowControllerType|PredefinedType:n|0000000000
IfcProxy|IfcProduct|ProxyType:n,Tag:s?|000000000
IfcPumpType|IfcFlowMovingDeviceType|PredefinedType:n|0000000000
IfcQuantityArea|IfcPhysicalSimpleQuantity|AreaValue:r|0000
IfcQuantityCount|IfcPhysicalSimpleQuantity|CountValue:u|0000
IfcQuantityLength|IfcPhysicalSimpleQuantity|LengthValue:r|0000
IfcQuantityTime|IfcPhysicalSimpleQuantity|TimeValue:r|0000
IfcQuantityVolume|IfcPhysicalSimpleQuantity|VolumeValue:r|0000
IfcQuantityWeight|IfcPhysicalSimpleQuantity|WeightValue:r|0000
IfcRadiusDimension|IfcDimensionCurveDirectedCallout||0
IfcRailing|IfcBuildingElement|PredefinedType:n?|000000000
IfcRailingType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcRamp|IfcBuildingElement|ShapeType:n|000000000
IfcRampFlight|IfcBuildingElement||00000000
IfcRampFlightType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcRationalBezierCurve|IfcBezierCurve|WeightsData:Lr|000000
IfcRectangleHollowProfileDef|IfcRectangleProfileDef|WallThickness:r,InnerFilletRadius:r?,OuterFilletRadius:r?|00000000
IfcRectangleProfileDef|IfcParameterizedProfileDef|XDim:r,YDim:r|00000
IfcRectangularPyramid|IfcCsgPrimitive3D|XLength:r,YLength:r,Height:r|0000
IfcRectangularTrimmedSurface|IfcBoundedSurface|BasisSurface:e,U1:r,V1:r,U2:r,V2:r,Usense:b,Vsense:b|0000000
IfcReferencesValueDocument||ReferencedDocument:e,ReferencingValues:E,Name:s?,Description:s?|0000
IfcRegularTimeSeries|IfcTimeSeries|TimeStep:r,Values:E|0000000000
IfcReinforcementBarProperties||TotalCrossSectionArea:r,SteelGrade:s,BarSurface:n?,EffectiveDepth:r?,NominalBarDiameter:r?,BarCount:u?|000000
IfcReinforcementDefinitionProperties|IfcPropertySetDefinition|DefinitionType:s?,ReinforcementSectionDefinitions:E|000000
IfcReinforcingBar|IfcReinforcingElement|NominalDiameter:r,CrossSectionArea:r,BarLength:r?,BarRole:n,BarSurface:n?|00000000000000
IfcReinforcingElement|IfcBuildingElementComponent|SteelGrade:s?|000000000|abstract
IfcReinforcingMesh|IfcReinforcingElement|MeshLength:r?,MeshWidth:r?,LongitudinalBarNominalDiameter:r,TransverseBarNominalDiameter:r,LongitudinalBarCrossSectionArea:r,TransverseBarCrossSectionArea:r,LongitudinalBarSpacing:r,TransverseBarSpacing:r|00000000000000000
IfcRelAggregates|IfcRelDecomposes||000000
IfcRelAssigns|IfcRelationship|RelatedObjects:E,RelatedObjectsType:n?|000000|abstract
IfcRelAssignsTasks|IfcRelAssignsToControl|TimeForTask:e?|00000000
IfcRelAssignsToActor|IfcRelAssigns|RelatingActor:e,ActingRole:e?|00000000
IfcRelAssignsToControl|IfcRelAssigns|RelatingControl:e|0000000
IfcRelAssignsToGroup|IfcRelAssigns|RelatingGroup:e|0000000
IfcRelAssignsToProcess|IfcRelAssigns|RelatingProcess:e,QuantityInProcess:e?|00000000
IfcRelAssignsToProduct|IfcRelAssigns|RelatingProduct:e|0000000
IfcRelAssignsToProjectOrder|IfcRelAssignsToControl||0000000
IfcRelAssignsToResource|IfcRelAssigns|RelatingResource:e|0000000
IfcRelAssociates|IfcRelationship|RelatedObjects:E|00000
IfcRelAssociatesAppliedValue|IfcRelAssociates|RelatingAppliedValue:e|000000
IfcRelAssociatesApproval|IfcRelAssociates|RelatingApproval:e|000000
IfcRelAssociatesClassification|IfcRelAssociates|RelatingClassification:e|000000
IfcRelAssociatesConstraint|IfcRelAssociates|Intent:s,RelatingConstraint:e|0000000
IfcRelAssociatesDocument|IfcRelAssociates|RelatingDocument:e|000000
IfcRelAssociatesLibrary|IfcRelAssociates|RelatingLibrary:e|000000
IfcRelAssociatesMaterial|IfcRelAssociates|RelatingMaterial:e|000000
IfcRelAssociatesProfileProperties|IfcRelAssociates|RelatingProfileProperties:e,ProfileSectionLocation:e?,ProfileOrientation:v?|00000000
IfcRelConnects|IfcRelationship||0000|abstract
IfcRelConnectsElements|IfcRelConnects|ConnectionGeometry:e?,RelatingElement:e,RelatedElement:e|0000000
IfcRelConnectsPathElements|IfcRelConnectsElements|RelatingPriorities:Li,RelatedPriorities:Li,RelatedConnectionType:n,RelatingConnectionType:n|00000000000
IfcRelConnectsPortToElement|IfcRelConnects|RelatingPort:e,RelatedElement:e|000000
IfcRelConnectsPorts|IfcRelConnects|RelatingPort:e,RelatedPort:e,RealizingElement:e?|0000000
IfcRelConnectsStructuralActivity|IfcRelConnects|RelatingElement:e,RelatedStructuralActivity:e|000000
IfcRelConnectsStructuralElement|IfcRelConnects|RelatingElement:e,RelatedStructuralMember:e|000000
IfcRelConnectsStructuralMember|IfcRelConnects|RelatingStructuralMember:e,RelatedStructuralConnection:e,AppliedCondition:e?,AdditionalConditions:e?,SupportedLength:r?,ConditionCoordinateSystem:e?|0000000000
IfcRelConnectsWithEccentricity|IfcRelConnectsStructuralMember|ConnectionConstraint:e|00000000000
IfcRelConnectsWithRealizingElements|IfcRelConnectsElements|RealizingElements:E,ConnectionType:s?|000000000
IfcRelContainedInSpatialStructure|IfcRelConnects|RelatedElements:E,RelatingStructure:e|000000
IfcRelCoversBldgElements|IfcRelConnects|RelatingBuildingElement:e,RelatedCoverings:E|000000
IfcRelCoversSpaces|IfcRelConnects|RelatedSpace:e,RelatedCoverings:E|000000
IfcRelDecomposes|IfcRelationship|RelatingObject:e,RelatedObjects:E|000000|abstract
IfcRelDefines|IfcRelationship|RelatedObjects:E|00000|abstract
IfcRelDefinesByProperties|IfcRelDefines|RelatingPropertyDefinition:e|000000
IfcRelDefinesByType|IfcRelDefines|RelatingType:e|000000
IfcRelFillsElement|IfcRelConnects|RelatingOpeningElement:e,RelatedBuildingElement:e|000000
IfcRelFlowControlElements|IfcRelConnects|RelatedControlElements:E,RelatingFlowElement:e|000000
IfcRelInteractionRequirements|IfcRelConnects|DailyInteraction:u?,ImportanceRating:r?,LocationOfInteraction:e?,RelatedSpaceProgram:e,RelatingSpaceProgram:e|000000000
IfcRelNests|IfcRelDecomposes||000000
IfcRelOccupiesSpaces|IfcRelAssignsToActor||00000000
IfcRelOverridesProperties|IfcRelDefinesByProperties|OverridingProperties:E|0000000
IfcRelProjectsElement|IfcRelConnects|RelatingElement:e,RelatedFeatureElement:e|000000
IfcRelReferencedInSpatialStructure|IfcRelConnects|RelatedElements:E,RelatingStructure:e|000000
IfcRelSchedulesCostItems|IfcRelAssignsToControl||0000000
IfcRelSequence|IfcRelConnects|RelatingProcess:e,RelatedProcess:e,TimeLag:r,SequenceType:n|00000000
IfcRelServicesBuildings|IfcRelConnects|RelatingSystem:e,RelatedBuildings:E|000000
IfcRelSpaceBoundary|IfcRelConnects|RelatingSpace:e,RelatedBuildingElement:e?,ConnectionGeometry:e?,PhysicalOrVirtualBoundary:n,InternalOrExternalBoundary:n|000000000
IfcRelVoidsElement|IfcRelConnects|RelatingBuildingElement:e,RelatedOpeningElement:e|000000
IfcRelationship|IfcRoot||0000|abstract
IfcRelaxation||RelaxationValue:r,InitialStress:r|00
IfcRepresentation||ContextOfItems:e,RepresentationIdentifier:s?,RepresentationType:s?,Items:E|0000
IfcRepresentationContext||ContextIdentifier:s?,ContextType:s?|00
IfcRepresentationItem||||abstract
IfcRepresentationMap||MappingOrigin:e,MappedRepresentation:e|00
IfcResource|IfcObject||00000|abstract
IfcRevolvedAreaSolid|IfcSweptAreaSolid|Axis:e,Angle:r|0000
IfcRibPlateProfileProperties|IfcProfileProperties|Thickness:r?,RibHeight:r?,RibWidth:r?,RibSpacing:r?,Direction:n|0000000
IfcRightCircularCone|IfcCsgPrimitive3D|Height:r,BottomRadius:r|000
IfcRightCircularCylinder|IfcCsgPrimitive3D|Height:r,Radius:r|000
IfcRoof|IfcBuildingElement|ShapeType:n|000000000
IfcRoot||GlobalId:s,OwnerHistory:e,Name:s?,Description:s?|0000|abstract
IfcRoundedEdgeFeature|IfcEdgeFeature|Radius:r?|0000000000
IfcRoundedRectangleProfileDef|IfcRectangleProfileDef|RoundingRadius:r|000000
IfcSIUnit|IfcNamedUnit|Prefix:n?,Name:n|1000
IfcSanitaryTerminalType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcScheduleTimeControl|IfcControl|ActualStart:e?,EarlyStart:e?,LateStart:e?,ScheduleStart:e?,ActualFinish:e?,EarlyFinish:e?,LateFinish:e?,ScheduleFinish:e?,ScheduleDuration:r?,ActualDuration:r?,RemainingTime:r?,FreeFloat:r?,TotalFloat:r?,IsCritical:b?,StatusTime:e?,StartFloat:r?,FinishFloat:r?,Completion:r?|00000000000000000000000
IfcSectionProperties||SectionType:n,StartProfile:e,EndProfile:e?|000
IfcSectionReinforcementProperties||LongitudinalStartPosition:r,LongitudinalEndPosition:r,TransversePosition:r?,ReinforcementRole:n,SectionDefinition:e,CrossSectionReinforcementDefinitions:E|000000
IfcSectionedSpine|IfcGeometricRepresentationItem|SpineCurve:e,CrossSections:E,CrossSectionPositions:E|000
IfcSensorType|IfcDistributionControlElementType|PredefinedType:n|0000000000
IfcServiceLife|IfcControl|ServiceLifeType:n,ServiceLifeDuration:r|0000000
IfcServiceLifeFactor|IfcPropertySetDefinition|PredefinedType:n,UpperValue:v?,MostUsedValue:v,LowerValue:v?|00000000
IfcShapeAspect||ShapeRepresentations:E,Name:s?,Description:s?,ProductDefinitional:b,PartOfProductDefinitionShape:e|00000
IfcShapeModel|IfcRepresentation||0000|abstract
IfcShapeRepresentation|IfcShapeModel||0000
IfcShellBasedSurfaceModel|IfcGeometricRepresentationItem|SbsmBoundary:E|0
IfcSimpleProperty|IfcProperty||00|abstract
IfcSite|IfcSpatialStructureElement|RefLatitude:Li?,RefLongitude:Li?,RefElevation:r?,LandTitleNumber:s?,SiteAddress:e?|00000000000000
IfcSlab|IfcBuildingElement|PredefinedType:n?|000000000
IfcSlabType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcSlippageConnectionCondition|IfcStructuralConnectionCondition|SlippageX:r?,SlippageY:r?,SlippageZ:r?|0000
IfcSolidModel|IfcGeometricRepresentationItem|||abstract
IfcSoundProperties|IfcPropertySetDefinition|IsAttenuating:b,SoundScale:n?,SoundValues:E|0000000
IfcSoundValue|IfcPropertySetDefinition|SoundLevelTimeSeries:e?,Frequency:r,SoundLevelSingleValue:v?|0000000
IfcSpace|IfcSpatialStructureElement|InteriorOrExteriorSpace:n,ElevationWithFlooring:r?|00000000000
IfcSpaceHeaterType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcSpaceProgram|IfcControl|SpaceProgramIdentifier:s,MaxRequiredArea:r?,MinRequiredArea:r?,RequestedLocation:e?,StandardRequiredArea:r|0000000000
IfcSpaceThermalLoadProperties|IfcPropertySetDefinition|ApplicableValueRatio:r?,ThermalLoadSource:n,PropertySource:n,SourceDescription:s?,MaximumValue:r,MinimumValue:r?,ThermalLoadTimeSeriesValues:e?,UserDefinedThermalLoadSource:s?,UserDefinedPropertySource:s?,ThermalLoadType:n|00000000000000
IfcSpaceType|IfcSpatialStructureElementType|PredefinedType:n|0000000000
IfcSpatialStructureElement|IfcProduct|LongName:s?,CompositionType:n|000000000|abstract
IfcSpatialStructureElementType|IfcElementType||000000000|abstract
IfcSphere|IfcCsgPrimitive3D|Radius:r|00
IfcStackTerminalType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcStair|IfcBuildingElement|ShapeType:n|000000000
IfcStairFlight|IfcBuildingElement|NumberOfRiser:i?,NumberOfTreads:i?,RiserHeight:r?,TreadLength:r?|000000000000
IfcStairFlightType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcStructuralAction|IfcStructuralActivity|DestabilizingLoad:b,CausedBy:e?|00000000000|abstract
IfcStructuralActivity|IfcProduct|AppliedLoad:e,GlobalOrLocal:n|000000000|abstract
IfcStructuralAnalysisModel|IfcSystem|PredefinedType:n,OrientationOf2DPlane:e?,LoadedBy:E?,HasResults:E?|000000000
IfcStructuralConnection|IfcStructuralItem|AppliedCondition:e?|00000000|abstract
IfcStructuralConnectionCondition||Name:s?|0|abstract
IfcStructuralCurveConnection|IfcStructuralConnection||00000000
IfcStructuralCurveMember|IfcStructuralMember|PredefinedType:n|00000000
IfcStructuralCurveMemberVarying|IfcStructuralCurveMember||00000000
IfcStructuralItem|IfcProduct||0000000|abstract
IfcStructuralLinearAction|IfcStructuralAction|ProjectedOrTrue:n|000000000000
IfcStructuralLinearActionVarying|IfcStructuralLinearAction|VaryingAppliedLoadLocation:e,SubsequentAppliedLoads:E|00000000000000
IfcStructuralLoad||Name:s?|0|abstract
IfcStructuralLoadGroup|IfcGroup|PredefinedType:n,ActionType:n,ActionSource:n,Coefficient:r?,Purpose:s?|0000000000
IfcStructuralLoadLinearForce|IfcStructuralLoadStatic|LinearForceX:r?,LinearForceY:r?,LinearForceZ:r?,LinearMomentX:r?,LinearMomentY:r?,LinearMomentZ:r?|0000000
IfcStructuralLoadPlanarForce|IfcStructuralLoadStatic|PlanarForceX:r?,PlanarForceY:r?,PlanarForceZ:r?|0000
IfcStructuralLoadSingleDisplacement|IfcStructuralLoadStatic|DisplacementX:r?,DisplacementY:r?,DisplacementZ:r?,RotationalDisplacementRX:r?,RotationalDisplacementRY:r?,RotationalDisplacementRZ:r?|0000000
IfcStructuralLoadSingleDisplacementDistortion|IfcStructuralLoadSingleDisplacement|Distortion:r?|00000000
IfcStructuralLoadSingleForce|IfcStructuralLoadStatic|ForceX:r?,ForceY:r?,ForceZ:r?,MomentX:r?,MomentY:r?,MomentZ:r?|0000000
IfcStructuralLoadSingleForceWarping|IfcStructuralLoadSingleForce|WarpingMoment:r?|00000000
IfcStructuralLoadStatic|IfcStructuralLoad||0|abstract
IfcStructuralLoadTemperature|IfcStructuralLoadStatic|DeltaT_Constant:r?,DeltaT_Y:r?,DeltaT_Z:r?|0000
IfcStructuralMember|IfcStructuralItem||0000000|abstract
IfcStructuralPlanarAction|IfcStructuralAction|ProjectedOrTrue:n|000000000000
IfcStructuralPlanarActionVarying|IfcStructuralPlanarAction|VaryingAppliedLoadLocation:e,SubsequentAppliedLoads:E|00000000000000
IfcStructuralPointAction|IfcStructuralAction||00000000000
IfcStructuralPointConnection|IfcStructuralConnection||00000000
IfcStructuralPointReaction|IfcStructuralReaction||000000000
IfcStructuralProfileProperties|IfcGeneralProfileProperties|TorsionalConstantX:r?,MomentOfInertiaYZ:r?,MomentOfInertiaY:r?,MomentOfInertiaZ:r?,WarpingConstant:r?,ShearCentreZ:r?,ShearCentreY:r?,ShearDeformationAreaZ:r?,ShearDeformationAreaY:r?,MaximumSectionModulusY:r?,MinimumSectionModulusY:r?,MaximumSectionModulusZ:r?,MinimumSectionModulusZ:r?,TorsionalSectionModulus:r?,CentreOfGravityInX:r?,CentreOfGravityInY:r?|00000000000000000000000
IfcStructuralReaction|IfcStructuralActivity||000000000|abstract
IfcStructuralResultGroup|IfcGroup|TheoryType:n,ResultForLoadGroup:e?,IsLinear:b|00000000
IfcStructuralSteelProfileProperties|IfcStructuralProfileProperties|ShearAreaZ:r?,ShearAreaY:r?,PlasticShapeFactorY:r?,PlasticShapeFactorZ:r?|000000000000000000000000000
IfcStructuralSurfaceConnection|IfcStructuralConnection||00000000
IfcStructuralSurfaceMember|IfcStructuralMember|PredefinedType:n,Thickness:r?|000000000
IfcStructuralSurfaceMemberVarying|IfcStructuralSurfaceMember|SubsequentThickness:Lr,VaryingThicknessLocation:e|00000000000
IfcStructuredDimensionCallout|IfcDraughtingCallout||0
IfcStyleModel|IfcRepresentation||0000|abstract
IfcStyledItem|IfcRepresentationItem|Item:e?,Styles:E,Name:s?|000
IfcStyledRepresentation|IfcStyleModel||0000
IfcSubContractResource|IfcConstructionResource|SubContractor:e?,JobDescription:s?|00000000000
IfcSubedge|IfcEdge|ParentEdge:e|000
IfcSurface|IfcGeometricRepresentationItem|||abstract
IfcSurfaceCurveSweptAreaSolid|IfcSweptAreaSolid|Directrix:e,StartParam:r,EndParam:r,ReferenceSurface:e|000000
IfcSurfaceOfLinearExtrusion|IfcSweptSurface|ExtrudedDirection:e,Depth:r|0000
IfcSurfaceOfRevolution|IfcSweptSurface|AxisPosition:e|000
IfcSurfaceStyle|IfcPresentationStyle|Side:n,Styles:E|000
IfcSurfaceStyleLighting||DiffuseTransmissionColour:e,DiffuseReflectionColour:e,TransmissionColour:e,ReflectanceColour:e|0000
IfcSurfaceStyleRefraction||RefractionIndex:r?,DispersionFactor:r?|00
IfcSurfaceStyleRendering|IfcSurfaceStyleShading|Transparency:r?,DiffuseColour:v?,TransmissionColour:v?,DiffuseTransmissionColour:v?,ReflectionColour:v?,SpecularColour:v?,SpecularHighlight:v?,ReflectanceMethod:n|000000000
IfcSurfaceStyleShading||SurfaceColour:e|0
IfcSurfaceStyleWithTextures||Textures:E|0
IfcSurfaceTexture||RepeatS:b,RepeatT:b,TextureType:n,TextureTransform:e?|0000|abstract
IfcSweptAreaSolid|IfcSolidModel|SweptArea:e,Position:e|00|abstract
IfcSweptDiskSolid|IfcSolidModel|Directrix:e,Radius:r,InnerRadius:r?,StartParam:r,EndParam:r|00000
IfcSweptSurface|IfcSurface|SweptCurve:e,Position:e|00|abstract
IfcSwitchingDeviceType|IfcFlowControllerType|PredefinedType:n|0000000000
IfcSymbolStyle|IfcPresentationStyle|StyleOfSymbol:e|00
IfcSystem|IfcGroup||00000
IfcSystemFurnitureElementType|IfcFurnishingElementType||000000000
IfcTShapeProfileDef|IfcParameterizedProfileDef|Depth:r,FlangeWidth:r,WebThickness:r,FlangeThickness:r,FilletRadius:r?,FlangeEdgeRadius:r?,WebEdgeRadius:r?,WebSlope:r?,FlangeSlope:r?,CentreOfGravityInY:r?|0000000000000
IfcTable||Name:s,Rows:E|00
IfcTableRow||RowCells:E,IsHeading:b|00
IfcTankType|IfcFlowStorageDeviceType|PredefinedType:n|0000000000
IfcTask|IfcProcess|TaskId:s,Status:s?,WorkMethod:s?,IsMilestone:b,Priority:i?|0000000000
IfcTelecomAddress|IfcAddress|TelephoneNumbers:Ls?,FacsimileNumbers:Ls?,PagerNumber:s?,ElectronicMailAddresses:Ls?,WWWHomePageURL:s?|00000000
IfcTendon|IfcReinforcingElement|PredefinedType:n,NominalDiameter:r,CrossSectionArea:r,TensionForce:r?,PreStress:r?,FrictionCoefficient:r?,AnchorageSlip:r?,MinCurvatureRadius:r?|00000000000000000
IfcTendonAnchor|IfcReinforcingElement||000000000
IfcTerminatorSymbol|IfcAnnotationSymbolOccurrence|AnnotatedCurve:e|0000
IfcTextLiteral|IfcGeometricRepresentationItem|Literal:s,Placement:e,Path:n|000
IfcTextLiteralWithExtent|IfcTextLiteral|Extent:e,BoxAlignment:s|00000
IfcTextStyle|IfcPresentationStyle|TextCharacterAppearance:e?,TextStyle:e?,TextFontStyle:e|0000
IfcTextStyleFontModel|IfcPreDefinedTextFont|FontFamily:Ls?,FontStyle:s?,FontVariant:s?,FontWeight:s?,FontSize:v|000000
IfcTextStyleForDefinedFont||Colour:e,BackgroundColour:e?|00
IfcTextStyleTextModel||TextIndent:v?,TextAlign:s?,TextDecoration:s?,LetterSpacing:v?,WordSpacing:v?,TextTransform:s?,LineHeight:v?|0000000
IfcTextStyleWithBoxCharacteristics||BoxHeight:r?,BoxWidth:r?,BoxSlantAngle:r?,BoxRotateAngle:r?,CharacterSpacing:v?|00000
IfcTextureCoordinate||||abstract
IfcTextureCoordinateGenerator|IfcTextureCoordinate|Mode:s,Parameter:E|00
IfcTextureMap|IfcTextureCoordinate|TextureMaps:E|0
IfcTextureVertex||Coordinates:Lr|0
IfcThermalMaterialProperties|IfcMaterialProperties|SpecificHeatCapacity:r?,BoilingPoint:r?,FreezingPoint:r?,ThermalConductivity:r?|00000
IfcTimeSeries||Name:s,Description:s?,StartTime:e,EndTime:e,TimeSeriesDataType:n,DataOrigin:n,UserDefinedDataOrigin:s?,Unit:e?|00000000|abstract
IfcTimeSeriesReferenceRelationship||ReferencedTimeSeries:e,TimeSeriesReferences:E|00
IfcTimeSeriesSchedule|IfcControl|ApplicableDates:E?,TimeSeriesScheduleType:n,TimeSeries:e|00000000
IfcTimeSeriesValue||ListValues:E|0
IfcTopologicalRepresentationItem|IfcRepresentationItem|||abstract
IfcTopologyRepresentation|IfcShapeModel||0000
IfcTransformerType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcTransportElement|IfcElement|OperationType:n?,CapacityByWeight:r?,CapacityByNumber:u?|00000000000
IfcTransportElementType|IfcElementType|PredefinedType:n|0000000000
IfcTrapeziumProfileDef|IfcParameterizedProfileDef|BottomXDim:r,TopXDim:r,YDim:r,TopXOffset:r|0000000
IfcTrimmedCurve|IfcBoundedCurve|BasisCurve:e,Trim1:E,Trim2:E,SenseAgreement:b,MasterRepresentation:n|00000
IfcTubeBundleType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcTwoDirectionRepeatFactor|IfcOneDirectionRepeatFactor|SecondRepeatFactor:e|00
IfcTypeObject|IfcObjectDefinition|ApplicableOccurrence:s?,HasPropertySets:E?|000000
IfcTypeProduct|IfcTypeObject|RepresentationMaps:E?,Tag:s?|00000000
IfcUShapeProfileDef|IfcParameterizedProfileDef|Depth:r,FlangeWidth:r,WebThickness:r,FlangeThickness:r,FilletRadius:r?,EdgeRadius:r?,FlangeSlope:r?,CentreOfGravityInX:r?|00000000000
IfcUnitAssignment||Units:E|0
IfcUnitaryEquipmentType|IfcEnergyConversionDeviceType|PredefinedType:n|0000000000
IfcValveType|IfcFlowControllerType|PredefinedType:n|0000000000
IfcVector|IfcGeometricRepresentationItem|Orientation:e,Magnitude:r|00
IfcVertex|IfcTopologicalRepresentationItem||
IfcVertexBasedTextureMap||TextureVertices:E,TexturePoints:E|00
IfcVertexLoop|IfcLoop|LoopVertex:e|0
IfcVertexPoint|IfcVertex|VertexGeometry:e|0
IfcVibrationIsolatorType|IfcDiscreteAccessoryType|PredefinedType:n|0000000000
IfcVirtualElement|IfcElement||00000000
IfcVirtualGridIntersection||IntersectingAxes:E,OffsetDistances:Lr|00
IfcWall|IfcBuildingElement||00000000
IfcWallStandardCase|IfcWall||00000000
IfcWallType|IfcBuildingElementType|PredefinedType:n|0000000000
IfcWasteTerminalType|IfcFlowTerminalType|PredefinedType:n|0000000000
IfcWaterProperties|IfcMaterialProperties|IsPotable:b?,Hardness:r?,AlkalinityConcentration:r?,AcidityConcentration:r?,ImpuritiesContent:r?,PHLevel:r?,DissolvedSolidsContent:r?|00000000
IfcWindow|IfcBuildingElement|OverallHeight:r?,OverallWidth:r?|0000000000
IfcWindowLiningProperties|IfcPropertySetDefinition|LiningDepth:r?,LiningThickness:r?,TransomThickness:r?,MullionThickness:r?,FirstTransomOffset:r?,SecondTransomOffset:r?,FirstMullionOffset:r?,SecondMullionOffset:r?,ShapeAspectStyle:e?|0000000000000
IfcWindowPanelProperties|IfcPropertySetDefinition|OperationType:n,PanelPosition:n,FrameDepth:r?,FrameThickness:r?,ShapeAspectStyle:e?|000000000
IfcWindowStyle|IfcTypeProduct|ConstructionType:n,OperationType:n,ParameterTakesPrecedence:b,Sizeable:b|000000000000
IfcWorkControl|IfcControl|Identifier:s,CreationDate:e,Creators:E?,Purpose:s?,Duration:r?,TotalFloat:r?,StartTime:e,FinishTime:e?,WorkControlType:n?,UserDefinedControlType:s?|000000000000000|abstract
IfcWorkPlan|IfcWorkControl||000000000000000
IfcWorkSchedule|IfcWorkControl||000000000000000
IfcZShapeProfileDef|IfcParameterizedProfileDef|Depth:r,FlangeWidth:r,WebThickness:r,FlangeThickness:r,FilletRadius:r?,EdgeRadius:r?|000000000
IfcZone|IfcGroup||00000
"""
    /// Defined types with the kind of their underlying value (typed values in selects, ifcXML "-wrapper" elements).
    static let ifc2x3Types = "IfcAbsorbedDoseMeasure:r IfcAccelerationMeasure:r IfcAmountOfSubstanceMeasure:r IfcAngularVelocityMeasure:r IfcAreaMeasure:r IfcBoolean:b IfcBoxAlignment:s IfcComplexNumber:Lr IfcCompoundPlaneAngleMeasure:Li IfcContextDependentMeasure:r IfcCountMeasure:u IfcCurvatureMeasure:r IfcDayInMonthNumber:i IfcDaylightSavingHour:i IfcDescriptiveMeasure:s IfcDimensionCount:i IfcDoseEquivalentMeasure:r IfcDynamicViscosityMeasure:r IfcElectricCapacitanceMeasure:r IfcElectricChargeMeasure:r IfcElectricConductanceMeasure:r IfcElectricCurrentMeasure:r IfcElectricResistanceMeasure:r IfcElectricVoltageMeasure:r IfcEnergyMeasure:r IfcFontStyle:s IfcFontVariant:s IfcFontWeight:s IfcForceMeasure:r IfcFrequencyMeasure:r IfcGloballyUniqueId:s IfcHeatFluxDensityMeasure:r IfcHeatingValueMeasure:r IfcHourInDay:i IfcIdentifier:s IfcIlluminanceMeasure:r IfcInductanceMeasure:r IfcInteger:i IfcIntegerCountRateMeasure:i IfcIonConcentrationMeasure:r IfcIsothermalMoistureCapacityMeasure:r IfcKinematicViscosityMeasure:r IfcLabel:s IfcLengthMeasure:r IfcLinearForceMeasure:r IfcLinearMomentMeasure:r IfcLinearStiffnessMeasure:r IfcLinearVelocityMeasure:r IfcLogical:b IfcLuminousFluxMeasure:r IfcLuminousIntensityDistributionMeasure:r IfcLuminousIntensityMeasure:r IfcMagneticFluxDensityMeasure:r IfcMagneticFluxMeasure:r IfcMassDensityMeasure:r IfcMassFlowRateMeasure:r IfcMassMeasure:r IfcMassPerLengthMeasure:r IfcMinuteInHour:i IfcModulusOfElasticityMeasure:r IfcModulusOfLinearSubgradeReactionMeasure:r IfcModulusOfRotationalSubgradeReactionMeasure:r IfcModulusOfSubgradeReactionMeasure:r IfcMoistureDiffusivityMeasure:r IfcMolecularWeightMeasure:r IfcMomentOfInertiaMeasure:r IfcMonetaryMeasure:r IfcMonthInYearNumber:i IfcNormalisedRatioMeasure:r IfcNumericMeasure:u IfcPHMeasure:r IfcParameterValue:r IfcPlanarForceMeasure:r IfcPlaneAngleMeasure:r IfcPositiveLengthMeasure:r IfcPositivePlaneAngleMeasure:r IfcPositiveRatioMeasure:r IfcPowerMeasure:r IfcPresentableText:s IfcPressureMeasure:r IfcRadioActivityMeasure:r IfcRatioMeasure:r IfcReal:r IfcRotationalFrequencyMeasure:r IfcRotationalMassMeasure:r IfcRotationalStiffnessMeasure:r IfcSecondInMinute:r IfcSectionModulusMeasure:r IfcSectionalAreaIntegralMeasure:r IfcShearModulusMeasure:r IfcSolidAngleMeasure:r IfcSoundPowerMeasure:r IfcSoundPressureMeasure:r IfcSpecificHeatCapacityMeasure:r IfcSpecularExponent:r IfcSpecularRoughness:r IfcTemperatureGradientMeasure:r IfcText:s IfcTextAlignment:s IfcTextDecoration:s IfcTextFontName:s IfcTextTransformation:s IfcThermalAdmittanceMeasure:r IfcThermalConductivityMeasure:r IfcThermalExpansionCoefficientMeasure:r IfcThermalResistanceMeasure:r IfcThermalTransmittanceMeasure:r IfcThermodynamicTemperatureMeasure:r IfcTimeMeasure:r IfcTimeStamp:i IfcTorqueMeasure:r IfcVaporPermeabilityMeasure:r IfcVolumeMeasure:r IfcVolumetricFlowRateMeasure:r IfcWarpingConstantMeasure:r IfcWarpingMomentMeasure:r IfcYearNumber:i"
}
