// Oanarina Archi Tool — GPL-3.0-or-later
import Foundation

/// Menu-bar translations (SYS-026): menu titles, submenus and the most used menu items, in the same order as
/// `L10n.table` (ro, de, fr, es, it). Items without a translation stay English.
extension L10n {
    static let menuTable: [String: [String]] = [
        "Draw": ["Desenare", "Zeichnen", "Dessin", "Dibujo", "Disegno"],
        "Modify": ["Modificare", "Ändern", "Modifier", "Modificar", "Modifica"],
        "Model": ["Model", "Modell", "Modèle", "Modelo", "Modello"],
        "Tools": ["Unelte", "Werkzeuge", "Outils", "Herramientas", "Strumenti"],
        "More Building Tools": ["Alte unelte de construcție", "Weitere Bauwerkzeuge", "Autres outils de construction", "Más herramientas de construcción", "Altri strumenti edilizi"],
        "Rooms & Areas": ["Încăperi și suprafețe", "Räume und Flächen", "Pièces et surfaces", "Habitaciones y áreas", "Locali e aree"],
        "Documentation": ["Documentație", "Dokumentation", "Documentation", "Documentación", "Documentazione"],
        "System Variables": ["Variabile de sistem", "Systemvariablen", "Variables système", "Variables del sistema", "Variabili di sistema"],
        "All Commands": ["Toate comenzile", "Alle Befehle", "Toutes les commandes", "Todos los comandos", "Tutti i comandi"],
        "Selection Tools": ["Unelte de selecție", "Auswahlwerkzeuge", "Outils de sélection", "Herramientas de selección", "Strumenti di selezione"],
        "Groups & Isolation": ["Grupuri și izolare", "Gruppen und Isolieren", "Groupes et isolement", "Grupos y aislamiento", "Gruppi e isolamento"],
        "3D View": ["Vedere 3D", "3D-Ansicht", "Vue 3D", "Vista 3D", "Vista 3D"],
        "Float Panel": ["Panou flotant", "Schwebendes Fenster", "Panneau flottant", "Panel flotante", "Pannello mobile"],
        "Open Recent": ["Deschide recente", "Zuletzt geöffnet", "Ouvrir l’élément récent", "Abrir reciente", "Apri recenti"],
        "New from Template": ["Nou din șablon", "Neu aus Vorlage", "Nouveau à partir d’un modèle", "Nuevo desde plantilla", "Nuovo da modello"],
        "Schedules (CSV)": ["Tabele (CSV)", "Listen (CSV)", "Nomenclatures (CSV)", "Tablas de planificación (CSV)", "Abachi (CSV)"],
        // Coverage menus of the Tools menu.
        "Draw More": ["Alte desene", "Weitere Zeichenbefehle", "Autres dessins", "Más dibujo", "Altro disegno"],
        "Construction": ["Construcții geometrice", "Konstruktion", "Construction", "Construcción", "Costruzione"],
        "Modify More": ["Alte modificări", "Weitere Änderungen", "Autres modifications", "Más modificación", "Altre modifiche"],
        "Clipboard & Selection": ["Clipboard și selecție", "Zwischenablage und Auswahl", "Presse-papiers et sélection", "Portapapeles y selección", "Appunti e selezione"],
        "Dimensions More": ["Alte cote", "Weitere Bemaßungen", "Autres cotes", "Más cotas", "Altre quote"],
        "Text & Tables": ["Text și tabele", "Text und Tabellen", "Texte et tableaux", "Texto y tablas", "Testo e tabelle"],
        "Parametric": ["Parametric", "Parametrisch", "Paramétrique", "Paramétrico", "Parametrico"],
        "Blocks & Attributes": ["Blocuri și atribute", "Blöcke und Attribute", "Blocs et attributs", "Bloques y atributos", "Blocchi e attributi"],
        "Layers": ["Straturi", "Layer", "Calques", "Capas", "Layer"],
        "BIM Data": ["Date BIM", "BIM-Daten", "Données BIM", "Datos BIM", "Dati BIM"],
        "Structure": ["Structură", "Tragwerk", "Structure", "Estructura", "Struttura"],
        "Site More": ["Alte unelte de teren", "Weitere Geländewerkzeuge", "Autres outils de site", "Más emplazamiento", "Altro sito"],
        "Surfaces & Mesh": ["Suprafețe și rețele", "Flächen und Netze", "Surfaces et maillages", "Superficies y mallas", "Superfici e mesh"],
        "Analysis": ["Analiză", "Analyse", "Analyse", "Análisis", "Analisi"],
        "Exchange": ["Schimb de date", "Datenaustausch", "Échange", "Intercambio", "Scambio"],
        "File": ["Fișier", "Datei", "Fichier", "Archivo", "File"],
        "Tools & Scripting": ["Unelte și scripturi", "Werkzeuge und Skripte", "Outils et scripts", "Herramientas y scripts", "Strumenti e script"],
        "Settings": ["Setări", "Einstellungen", "Réglages", "Ajustes", "Impostazioni"],
        "Plot Styles": ["Stiluri de plotare", "Plotstile", "Styles de tracé", "Estilos de trazado", "Stili di stampa"],
        "Start & Templates": ["Start și șabloane", "Start und Vorlagen", "Démarrage et modèles", "Inicio y plantillas", "Avvio e modelli"],
        "Help": ["Ajutor", "Hilfe", "Aide", "Ayuda", "Aiuto"],
        "Styles, Patterns & Occlusion": ["Stiluri, hașuri și ocluzie", "Stile, Muster und Okklusion", "Styles, motifs et occlusion", "Estilos, patrones y oclusión", "Stili, retini e occlusione"],
        // Round 12 dialogs.
        "Object Styles…": ["Stiluri de obiecte…", "Objektstile…", "Styles d’objets…", "Estilos de objeto…", "Stili oggetto…"],
        "Text Styles…": ["Stiluri de text…", "Textstile…", "Styles de texte…", "Estilos de texto…", "Stili di testo…"],
        "Image Adjust…": ["Ajustare imagine…", "Bild anpassen…", "Ajuster l’image…", "Ajustar imagen…", "Regola immagine…"],
        "Ambient Occlusion…": ["Ocluzie ambientală…", "Umgebungsverdeckung…", "Occlusion ambiante…", "Oclusión ambiental…", "Occlusione ambientale…"],
        "Material Fill Patterns…": ["Hașuri de materiale…", "Materialschraffuren…", "Motifs de matériaux…", "Patrones de materiales…", "Retini dei materiali…"],
        "Edit Text In Place": ["Editare text pe loc", "Text direkt bearbeiten", "Modifier le texte sur place", "Editar texto en el sitio", "Modifica testo sul posto"],
        "VR Headset View": ["Vizualizare cu cască VR", "VR-Brillen-Ansicht", "Vue casque VR", "Vista con visor VR", "Vista visore VR"],
        "Exchange More": ["Alte formate", "Weitere Formate", "Autres formats", "Más formatos", "Altri formati"],
        "Floor Pattern": ["Model de pardoseală", "Bodenmuster", "Motif de sol", "Patrón de suelo", "Motivo pavimento"],
        // Frequent menu items.
        "Line": ["Linie", "Linie", "Ligne", "Línea", "Linea"],
        "Polyline": ["Polilinie", "Polylinie", "Polyligne", "Polilínea", "Polilinea"],
        "Circle": ["Cerc", "Kreis", "Cercle", "Círculo", "Cerchio"],
        "Arc": ["Arc", "Bogen", "Arc", "Arco", "Arco"],
        "Rectangle": ["Dreptunghi", "Rechteck", "Rectangle", "Rectángulo", "Rettangolo"],
        "Move": ["Mutare", "Verschieben", "Déplacer", "Desplazar", "Sposta"],
        "Copy": ["Copiere", "Kopieren", "Copier", "Copiar", "Copia"],
        "Rotate": ["Rotire", "Drehen", "Rotation", "Girar", "Ruota"],
        "Scale": ["Scalare", "Skalieren", "Échelle", "Escala", "Scala"],
        "Mirror": ["Oglindire", "Spiegeln", "Miroir", "Simetría", "Specchio"],
        "Trim": ["Tăiere", "Stutzen", "Ajuster", "Recortar", "Taglia"],
        "Extend": ["Prelungire", "Dehnen", "Prolonger", "Alargar", "Estendi"],
        "Offset": ["Decalare", "Versetz", "Décaler", "Desfase", "Offset"],
        "Erase": ["Ștergere", "Löschen", "Effacer", "Borrar", "Cancella"],
        "Undo": ["Anulare", "Rückgängig", "Annuler", "Deshacer", "Annulla"],
        "Redo": ["Refacere", "Wiederholen", "Rétablir", "Rehacer", "Ripeti"],
        "Save": ["Salvare", "Sichern", "Enregistrer", "Guardar", "Salva"],
        "Open": ["Deschidere", "Öffnen", "Ouvrir", "Abrir", "Apri"],
        "New": ["Nou", "Neu", "Nouveau", "Nuevo", "Nuovo"],
        "Plot": ["Plotare", "Plotten", "Tracer", "Trazar", "Stampa"],
    ]
}
